# Generated by Django 2.2 on 2020-04-21 07:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('last_modified_time', models.DateTimeField()),
                ('item_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufracturer')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('category_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('zcrm_product_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM Product ID')),
                ('is_combined_product', models.BooleanField(verbose_name='Is Combined Product')),
                ('account_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account ID')),
                ('account_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('purchase_rate', models.IntegerField(verbose_name='Purchase Rate')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID')),
                ('tax_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Name')),
                ('tax_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Type')),
                ('tax_percentage', models.FloatField(verbose_name='Tax Percentage')),
                ('purchase_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Account Name')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Type')),
                ('is_taxable', models.BooleanField(verbose_name='Is Taxable')),
                ('is_returnable', models.BooleanField(verbose_name='Is Returnable')),
                ('tax_exemption_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Excemption Code')),
                ('total_initial_stock', models.FloatField(blank=True, null=True, verbose_name='Total Initial Stock')),
                ('stock_on_hand', models.FloatField(verbose_name='Stock On Hand')),
                ('available_stock', models.FloatField(verbose_name='Availabe Stock')),
                ('cf_strain_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Strain Name')),
                ('cf_cultivation_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cultivation Type')),
                ('cf_cannabis_grade_and_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cannabis Grade and Category')),
                ('cf_client_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Code')),
                ('cf_lab_file', models.URLField(blank=True, max_length=255, null=True, verbose_name='Lab File')),
                ('cf_pending_sale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pending Sale')),
                ('cf_potency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potency')),
                ('cf_cultivar_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cultivar Type')),
                ('cf_procurement_rep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Procurement Rep')),
                ('package_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('batched', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True), size=None)),
            ],
        ),
    ]
