# Generated by Django 2.2 on 2020-04-21 09:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='batched',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
