# Generated by Django 2.2 on 2020-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200421_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_potency',
            field=models.FloatField(blank=True, null=True, verbose_name='Potency'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_rate',
            field=models.FloatField(verbose_name='Purchase Rate'),
        ),
    ]
