# Generated by Django 2.2 on 2020-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='batched',
            new_name='batches',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item ID'),
        ),
    ]
