# Generated by Django 2.2 on 2020-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200421_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Availabe Stock'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_on_hand',
            field=models.FloatField(blank=True, null=True, verbose_name='Stock On Hand'),
        ),
    ]
