# Generated by Django 2.2 on 2020-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory_cf_cfi_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_cfi_published',
            field=models.BooleanField(default=False, verbose_name='CFI_Published'),
        ),
    ]
