# Generated by Django 2.2 on 2020-05-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200514_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_cfi_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='CFI_Published'),
        ),
    ]
