# Generated by Django 2.2 on 2020-05-26 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200514_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_cbc',
            field=models.FloatField(blank=True, null=True, verbose_name='CBC'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbca',
            field=models.FloatField(blank=True, null=True, verbose_name='CBCA'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbda',
            field=models.FloatField(blank=True, null=True, verbose_name='CBDA'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbdv',
            field=models.FloatField(blank=True, null=True, verbose_name='CBDV'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbga',
            field=models.FloatField(blank=True, null=True, verbose_name='CBGA'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbl',
            field=models.FloatField(blank=True, null=True, verbose_name='CBL'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cbn',
            field=models.FloatField(blank=True, null=True, verbose_name='CBN'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_d_8_thc',
            field=models.FloatField(blank=True, null=True, verbose_name='D8_THC'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_harvest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Harvest'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_ifp_farm',
            field=models.BooleanField(blank=True, null=True, verbose_name='IFP_Farm'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_lab_test_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lab Test Link'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_lpn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LPN'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_marge_per_unit',
            field=models.FloatField(blank=True, null=True, verbose_name='Margin Per Unit'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_metrc_manifest_number',
            field=models.TextField(blank=True, null=True, verbose_name='Metrc Manifest Number'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_metrc_packages',
            field=models.TextField(blank=True, null=True, verbose_name='Metrc Package'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_pending_sale_1_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pending Sale 1'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_pending_sale_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pending Sale 2'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_pending_sale_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pending Sale 3'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_pesticide_summary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pesticide Summary'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_procurement_confirmed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PnC'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_received_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Received Date'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_testing_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_thca',
            field=models.FloatField(blank=True, null=True, verbose_name='THCA'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_thcva',
            field=models.FloatField(blank=True, null=True, verbose_name='THCVA'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_vendor_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cf_cbd',
            field=models.FloatField(blank=True, null=True, verbose_name='CBD'),
        ),
    ]
