# Generated by Django 2.2 on 2020-06-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0002_auto_20200603_0906'),
        ('inventory', '0011_auto_20200526_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cultivar', to='cultivar.Cultivar', verbose_name='Cultivar'),
        ),
    ]
