# Generated by Django 2.2 on 2020-06-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200615_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_next_harvest_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
