# Generated by Django 2.2 on 2020-07-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0003_auto_20200703_1008'),
        ('inventory', '0016_auto_20200615_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labtest', to='labtest.LabTest', verbose_name='LabTest'),
        ),
    ]
