# Generated by Django 2.2 on 2020-07-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventory_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cf_alpha_humulene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_alpha_pinene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_alpha_terpineol',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_beta_caryophyllene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbc',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbca',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbd',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbda',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbdv',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbga',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbl',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_cbn',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_d_8_thc',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_geraniol',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_linalool',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_myrcene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_ocimene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_potency',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_r_limonene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_terpinolene',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_thca',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_thcva',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cf_valencene',
        ),
    ]
