# Generated by Django 2.2 on 2020-07-15 04:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20200710_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='actual_available_for_sale_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Available For Sale Stock'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='available_for_sale_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Available For Sale Stock'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_administrative_hold',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Administrative Hold'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_batch_blending',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Blending'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_batch_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Batch Notes'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_lab_test_results_box_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lab Test Results Box Url'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_lab_testing_status',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lab Testing Status'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_manufacturing_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_qa_intake_grading_sheet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qa Intake Grading Sheet Id'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inventory Account Id'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inventory Account Name'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Account Id'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='inventory',
            name='track_batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Track Batch Number'),
        ),
    ]
