# Generated by Django 2.2 on 2020-07-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20200716_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Name'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Type'),
        ),
    ]
