# Generated by Django 2.2 on 2020-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20200716_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_date_available',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
