# Generated by Django 2.2 on 2020-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20200717_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='actual_available_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Actual Available For Sale Stock'),
        ),
    ]
