# Generated by Django 2.2 on 2020-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_inventory_actual_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_lab_test_sample_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cf_lab_test_sample_id'),
        ),
    ]
