# Generated by Django 2.2 on 2020-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventory_cf_lab_test_sample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_metrc_source_package_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cf_metrc_source_package_id'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_quantity_estimate',
            field=models.FloatField(blank=True, null=True, verbose_name='cf_quantity_estimate'),
        ),
    ]
