# Generated by Django 2.2 on 2020-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20200814_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_market_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='cf_market_feedback'),
        ),
    ]
