# Generated by Django 2.2 on 2020-09-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0026_inventory_cf_market_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(verbose_name='feedback')),
                ('estimate_number', models.CharField(max_length=100, verbose_name='Estimate Number')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='inventory.Inventory', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
