# Generated by Django 2.2 on 2020-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20200922_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pre_tax_price',
            field=models.FloatField(blank=True, null=True, verbose_name='pre_tax_price'),
        ),
    ]
