# Generated by Django 2.2 on 2020-09-22 12:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20200922_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='item_id')),
                ('price_array', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='current_price_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Current Price Change'),
        ),
    ]
