# Generated by Django 2.2 on 2020-09-28 08:37

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0029_inventory_pre_tax_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InTransitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile_id', models.IntegerField(verbose_name='profile_id')),
                ('order_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transit_order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'In Transit order',
                'verbose_name_plural': 'In Transit orders',
                'unique_together': {('user', 'profile_id')},
            },
        ),
    ]
