# Generated by Django 2.2 on 2020-09-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_inventory_pre_tax_price'),
        ('inventory', '0029_auto_20200922_1244'),
    ]

    operations = [
    ]
