# Generated by Django 2.2 on 2020-10-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0030_intransitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=255, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('size', models.CharField(max_length=100, verbose_name='File Size')),
                ('file_type', models.CharField(max_length=50, verbose_name='File Type')),
                ('path', models.CharField(max_length=500, verbose_name='File Path')),
                ('status', models.CharField(choices=[('OPTIMIZING', 'Optimizing'), ('REQUESTED', 'Requested'), ('AVAILABLE', 'Available'), ('UPLOADING', 'Uploading'), ('ERROR', 'Error')], max_length=50, verbose_name='Status')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
