# Generated by Django 2.2 on 2020-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('OPTIMIZING', 'Optimizing'), ('REQUESTED', 'Requested'), ('AVAILABLE', 'Available'), ('UPLOADING', 'Uploading'), ('ERROR', 'Error')], default='UPLOADING', max_length=50, verbose_name='Status'),
        ),
    ]
