# Generated by Django 2.2 on 2020-10-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20201007_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
