# Generated by Django 2.2 on 2020-10-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20201007_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
