# Generated by Django 2.2 on 2020-10-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20201008_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='box_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Box ID'),
        ),
        migrations.AddField(
            model_name='documents',
            name='box_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Box Url'),
        ),
    ]
