# Generated by Django 2.2 on 2020-10-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_merge_20200925_0448'),
        ('inventory', '0035_auto_20201013_0458'),
    ]

    operations = [
    ]
