# Generated by Django 2.2 on 2020-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_merge_20201026_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary Image'),
        ),
    ]
