# Generated by Django 2.2 on 2020-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_documents_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doc Type'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('OPTIMIZING', 'Optimizing'), ('REQUESTED', 'Requested'), ('AVAILABLE', 'Available'), ('UPLOADING', 'Uploading'), ('ERROR', 'Error')], db_index=True, default='UPLOADING', max_length=50, verbose_name='Status'),
        ),
    ]
