# Generated by Django 2.2 on 2020-12-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20201104_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
