# Generated by Django 2.2 on 2020-12-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_documents_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_available_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_minimum_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Quantity'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_sample_in_house',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample In House'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_seller_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seller Position'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cf_farm_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Farm Price'),
        ),
    ]
