# Generated by Django 2.2 on 2020-12-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20201209_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='county_grown',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='County Grown'),
        ),
    ]
