# Generated by Django 2.2 on 2020-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_inventory_county_grown'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Thumbnail Url'),
        ),
    ]
