# Generated by Django 2.2 on 2020-12-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20201221_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Thumbnail Url'),
        ),
    ]
