# Generated by Django 2.2 on 2021-01-15 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_inventory_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='nutrients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
