# Generated by Django 2.2 on 2021-01-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0004_auto_20210122_1624'),
        ('inventory', '0046_inventory_ethics_and_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(blank=True, default=None, null=True, verbose_name='Harvest Date')),
                ('quantity_available', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Quantity Available')),
                ('need_lab_testing_service', models.BooleanField(verbose_name='Need Lab Testing Service')),
                ('grade_estimate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grade Estimate')),
                ('status', models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='pending_for_approval', max_length=255, verbose_name='Status')),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_inventory', to='cultivar.Cultivar', verbose_name='Cultivar')),
            ],
        ),
    ]
