# Generated by Django 2.2 on 2021-01-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_custominventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='best_contact_window_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Best Contact Window End'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='best_contact_window_start',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Best Contact Window Start'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='cultivation_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cultivation Type'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='item_category',
            field=models.CharField(blank=True, choices=[('smalls', 'Smalls'), ('tops', 'Tops')], max_length=255, null=True, verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimum Order Quantity'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='pricing_position',
            field=models.CharField(blank=True, choices=[('negotiable', 'Negotiable'), ('firm', 'Firm')], max_length=255, null=True, verbose_name='Pricing Position'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='product_availability_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Product Availability Date'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='product_quality_notes_or_misc',
            field=models.TextField(blank=True, null=True, verbose_name='Product Quality Notes Or Misc'),
        ),
    ]
