# Generated by Django 2.2 on 2021-02-04 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20210125_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominventory',
            name='best_contact_window_end',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='best_contact_window_start',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='cultivation_type',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='product_availability_date',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='product_quality_notes_or_misc',
        ),
        migrations.AddField(
            model_name='custominventory',
            name='batch_availability_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Batch Availability Date'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='best_contact_Day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=50, null=True, verbose_name='Best Contact Day Of Week'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='best_contact_time_from',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Best Contact Time From'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='best_contact_time_to',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Best Contact Time To'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='category_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category ID'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='category_name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Item Category Name'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custominventory',
            name='farm_ask_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Farm Ask Price'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='have_minimum_order_quantity',
            field=models.BooleanField(default=False, verbose_name='Minimum Order Quantity'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='product_quality_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Product Quality Notes'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='transportation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transportation / Sample Pickup'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='cultivar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_inventory', to='cultivar.Cultivar', verbose_name='Cultivar'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Minimum Order Quantity(lbs)'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='pricing_position',
            field=models.CharField(blank=True, choices=[('Negotiable', 'Negotiable'), ('Firm', 'Firm'), ('Min Quantity', 'Min Quantity'), ('Offers Open', 'Offers Open')], max_length=255, null=True, verbose_name='Pricing Position'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='vendor_name',
            field=models.CharField(default='', max_length=255, verbose_name='Vendor Name'),
            preserve_default=False,
        ),
    ]
