# Generated by Django 2.2 on 2021-02-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20210204_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='zoho_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zoho Item ID'),
        ),
    ]
