# Generated by Django 2.2 on 2021-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_custominventory_zoho_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='minimum_order_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Order Quantity(lbs)'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='quantity_available',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity Available'),
        ),
    ]
