# Generated by Django 2.2 on 2021-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_auto_20210210_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='category_name',
            field=models.CharField(blank=True, choices=[('Wholesale - Flower', 'Wholesale - Flower'), ('In the Field', 'In the Field'), ('Flower - Tops', 'Flower - Tops'), ('Flower - Bucked Untrimmed', 'Flower - Bucked Untrimmed'), ('Flower - Bucked Untrimmed - Seeded', 'Flower - Bucked Untrimmed - Seeded'), ('Flower - Bucked Untrimmed - Contaminated', 'Flower - Bucked Untrimmed - Contaminated'), ('Flower - Small', 'Flower - Small'), ('Trim', 'Trim'), ('Packaged Goods', 'Packaged Goods'), ('Isolates', 'Isolates'), ('Isolates - CBD', 'Isolates - CBD'), ('Isolates - THC', 'Isolates - THC'), ('Isolates - CBG', 'Isolates - CBG'), ('Isolates - CBN', 'Isolates - CBN'), ('Wholesale - Concentrates', 'Wholesale - Concentrates'), ('Crude Oil', 'Crude Oil'), ('Crude Oil - THC', 'Crude Oil - THC'), ('Crude Oil - CBD', 'Crude Oil - CBD'), ('Distillate Oil', 'Distillate Oil'), ('Distillate Oil - THC', 'Distillate Oil - THC'), ('Distillate Oil - CBD', 'Distillate Oil - CBD'), ('Shatter', 'Shatter'), ('Sauce', 'Sauce'), ('Crumble', 'Crumble'), ('Kief', 'Kief'), ('Lab Testing', 'Lab Testing'), ('Terpenes', 'Terpenes'), ('Terpenes - Cultivar Specific', 'Terpenes - Cultivar Specific'), ('Terpenes - Cultivar Blended', 'Terpenes - Cultivar Blended'), ('Services', 'Services'), ('QC', 'QC'), ('Transport', 'Transport'), ('Secure Cash Handling', 'Secure Cash Handling')], max_length=225, null=True, verbose_name='Item Category Name'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='farm_ask_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Farm Ask Price'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='grade_estimate',
            field=models.CharField(blank=True, choices=[('Smalls A', 'Smalls A'), ('Smalls B', 'Smalls B'), ('Smalls C', 'Smalls C'), ('Tops A', 'Tops A'), ('Tops AA', 'Tops AA'), ('Tops AAA', 'Tops AAA'), ('Tops B', 'Tops B'), ('Tops C', 'Tops C'), ('Trim', 'Trim')], max_length=255, null=True, verbose_name='Grade Estimate'),
        ),
    ]
