# Generated by Django 2.2 on 2021-02-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_remove_custominventory_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custominventory',
            options={'verbose_name': 'Custom Inventory', 'verbose_name_plural': 'Custom Inventory Items'},
        ),
    ]
