# Generated by Django 2.2 on 2021-02-16 08:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_auto_20210212_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='approved_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='approved_on',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Approved on'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='created_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='grade_estimate',
            field=models.CharField(blank=True, choices=[('Smalls A', 'Smalls A'), ('Smalls B', 'Smalls B'), ('Smalls C', 'Smalls C'), ('Tops A', 'Tops A'), ('Tops AA', 'Tops AA'), ('Tops AAA', 'Tops AAA'), ('Tops B', 'Tops B'), ('Tops C', 'Tops C')], max_length=255, null=True, verbose_name='Grade Estimate'),
        ),
    ]
