# Generated by Django 2.2 on 2021-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_auto_20210216_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='approved_on',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved on'),
        ),
    ]
