# Generated by Django 2.2 on 2021-02-17 11:37

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20210216_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='payment_method',
            field=inventory.models.ChoiceArrayField(base_field=models.CharField(choices=[('Cash', 'Cash'), ('ACH', 'ACH'), ('Check', 'Check'), ('Bank Wire', 'Bank Wire')], max_length=100, verbose_name='Payment Method'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('14-30 Days', '14-30 Days'), ('21 Days', '21 Days'), ('7-14 Days', '7-14 Days'), ('COD', 'COD')], max_length=50, null=True, verbose_name='Payment Terms'),
        ),
    ]
