# Generated by Django 2.2 on 2021-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_auto_20210217_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='books_po_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoho Books Purchase Order id'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Order Number'),
        ),
    ]
