# Generated by Django 2.2 on 2021-02-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_auto_20210222_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='procurement_rep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Procurement Rep'),
        ),
    ]
