# Generated by Django 2.2 on 2021-03-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_inventory_cf_farm_price_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='is_combined_product',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Combined Product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_returnable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Returnable'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_taxable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Taxable'),
        ),
    ]
