# Generated by Django 2.2 on 2021-03-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_custominventory_crm_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='procurement_rep_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Procurement Rep name'),
        ),
    ]
