# Generated by Django 2.2 on 2021-03-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_custominventory_procurement_rep_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custominventory',
            options={'verbose_name': 'Vendor Inventory', 'verbose_name_plural': 'Vendor Inventory Items'},
        ),
    ]
