# Generated by Django 2.2 on 2021-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_auto_20210310_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventorySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_thc_max', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Max)')),
                ('total_thc_min', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Min)')),
                ('batch_varities', models.IntegerField(blank=True, null=True, verbose_name='Batches')),
                ('average', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Average $/lb')),
                ('total_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total Value $')),
                ('smalls_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Smalls(lbs)')),
                ('tops_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Tops(lbs)')),
                ('total_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total(lbs)')),
                ('trim_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Trim quantity')),
            ],
            options={
                'verbose_name': 'Daily Inventory Summary',
                'verbose_name_plural': 'Daily Inventory Summary',
            },
        ),
    ]
