# Generated by Django 2.2 on 2021-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_dailyinventorysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinventorysummary',
            name='county_grown',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='County Grown'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyinventorysummary',
            unique_together={('date', 'county_grown')},
        ),
    ]
