# Generated by Django 2.2 on 2021-03-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_auto_20210317_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='County Grown')),
            ],
            options={
                'verbose_name': 'Inventory County',
                'verbose_name_plural': 'Distinct Counties',
            },
        ),
        migrations.CreateModel(
            name='CountyDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_thc_max', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Max)')),
                ('total_thc_min', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Min)')),
                ('batch_varities', models.IntegerField(blank=True, null=True, verbose_name='Batches')),
                ('average', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Average $/lb')),
                ('total_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total Value $')),
                ('smalls_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Smalls(lbs)')),
                ('tops_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Tops(lbs)')),
                ('total_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total(lbs)')),
                ('trim_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Trim quantity')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.County', verbose_name='County')),
            ],
            options={
                'verbose_name': 'Daily County Summary',
                'verbose_name_plural': 'Daily County Summary',
                'unique_together': {('date', 'county')},
            },
        ),
        migrations.CreateModel(
            name='DailyInventoryAggrigatedSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_thc_max', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Max)')),
                ('total_thc_min', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Min)')),
                ('batch_varities', models.IntegerField(blank=True, null=True, verbose_name='Batches')),
                ('average', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Average $/lb')),
                ('total_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total Value $')),
                ('smalls_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Smalls(lbs)')),
                ('tops_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Tops(lbs)')),
                ('total_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total(lbs)')),
                ('trim_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Trim quantity')),
            ],
            options={
                'verbose_name': 'Daily Inventory Summary',
                'verbose_name_plural': 'Daily Inventory Summary',
            },
        ),
        migrations.DeleteModel(
            name='DailyInventorySummary',
        ),
    ]
