# Generated by Django 2.2 on 2021-03-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_auto_20210317_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyinventoryaggrigatedsummary',
            options={'verbose_name': 'Daily Inventory Aggrigated Summary', 'verbose_name_plural': 'Daily Inventory  Aggrigated Summary'},
        ),
    ]
