# Generated by Django 2.2 on 2021-03-30 13:37

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_historicalinventory_inventoryitemschangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemschangerequest',
            name='payment_method',
            field=inventory.models.ChoiceArrayField(base_field=models.CharField(choices=[('Cash', 'Cash'), ('ACH', 'ACH'), ('Check', 'Check'), ('Bank Wire', 'Bank Wire')], max_length=100, verbose_name='Payment Method'), blank=True, default=list, size=None),
        ),
    ]
