# Generated by Django 2.2 on 2021-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_auto_20210330_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='countydailysummary',
            name='average_thc',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Avg THC'),
        ),
        migrations.AddField(
            model_name='dailyinventoryaggrigatedsummary',
            name='average_thc',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Avg THC'),
        ),
    ]
