# Generated by Django 2.2 on 2021-04-05 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import inventory.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_auto_20210331_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.FloatField(blank=True, null=True, verbose_name='Quantity Available')),
                ('batch_availability_date', models.DateField(blank=True, default=None, null=True, verbose_name='Batch Availability Date')),
                ('farm_price', models.FloatField(blank=True, null=True, verbose_name='Farm Price')),
                ('pricing_position', models.CharField(blank=True, choices=[('Negotiable', 'Negotiable'), ('Firm', 'Firm'), ('Min Quantity', 'Min Quantity'), ('Offers Open', 'Offers Open')], max_length=255, null=True, verbose_name='Pricing Position')),
                ('have_minimum_order_quantity', models.BooleanField(default=False, verbose_name='Minimum Order Quantity')),
                ('minimum_order_quantity', models.FloatField(blank=True, null=True, verbose_name='Minimum Order Quantity(lbs)')),
                ('payment_terms', models.CharField(blank=True, choices=[('60 Days', '60 Days'), ('21 Days', '21 Days')], max_length=50, null=True, verbose_name='Payment Terms')),
                ('payment_method', inventory.fields.ChoiceArrayField(base_field=models.CharField(choices=[('Cash', 'Cash'), ('ACH', 'ACH'), ('Check', 'Check'), ('Bank Wire', 'Bank Wire')], max_length=100, verbose_name='Payment Method'), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='pending_for_approval', max_length=255, verbose_name='Status')),
                ('created_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Created by')),
                ('approved_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Approved by')),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved on')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='inventory.Inventory', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Item Edit Request',
                'verbose_name_plural': 'Item Edit Requests',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemQuantityAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='pending_for_approval', max_length=255, verbose_name='Status')),
                ('po_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Order id')),
                ('po_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Order Number')),
                ('created_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Created by')),
                ('approved_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Approved by')),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved on')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_additions', to='inventory.Inventory', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Quantity Addition',
                'verbose_name_plural': 'Quantity Additions',
            },
        ),
        migrations.AlterModelOptions(
            name='dailyinventoryaggrigatedsummary',
            options={'verbose_name': 'Daily Inventory Aggregated Summary', 'verbose_name_plural': 'Daily Inventory  Aggregated Summary'},
        ),
        migrations.DeleteModel(
            name='InventoryItemsChangeRequest',
        ),
    ]
