# Generated by Django 2.2 on 2021-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_auto_20210407_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='marketplace_status',
            field=models.CharField(choices=[('Available', 'Available'), ('In-Testing', 'In-Testing'), ('Processing', 'Processing'), ('Flowering', 'Flowering'), ('Vegging', 'Vegging')], default='In-Testing', max_length=225, verbose_name='Marketplace Status'),
        ),
    ]
