# Generated by Django 2.2 on 2021-04-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_auto_20210412_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemedit',
            name='marketplace_status',
            field=models.CharField(blank=True, choices=[('Under Contract', 'Under Contract'), ('Sold', 'Sold'), ('Pending Sale', 'Pending Sale'), ('Available', 'Available'), ('In-Testing', 'In-Testing'), ('Processing', 'Processing'), ('Flowering', 'Flowering'), ('Vegging', 'Vegging')], max_length=225, null=True, verbose_name='Marketplace Status'),
        ),
    ]
