# Generated by Django 2.2 on 2021-05-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0079_inventoryitemedit_marketplace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='mobile_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mobile Url'),
        ),
    ]
