# Generated by Django 2.2 on 2021-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0080_documents_mobile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='mobile_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mobile Url'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='mobile_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mobile Url'),
        ),
    ]
