# Generated by Django 2.2 on 2021-05-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0082_auto_20210507_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='appellations',
            new_name='appellation',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='appellations',
            new_name='appellation',
        ),
    ]
