# Generated by Django 2.2 on 2021-05-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_auto_20210507_0526'),
        ('inventory', '0082_auto_20210506_1135'),
    ]

    operations = [
    ]
