# Generated by Django 2.2 on 2021-05-07 10:15

from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    CustomInventory = apps.get_model("inventory", "CustomInventory")
    LicenseProfile = apps.get_model("brand", "LicenseProfile")
    for item in CustomInventory.objects.all():
        if item.vendor_name:
            qs = LicenseProfile.objects.filter(name=item.vendor_name)
            if qs.exists():
                item.license_profile = qs.latest('created_on')
                item.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0071_nurseryoverview'),
        ('inventory', '0084_merge_20210507_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='license_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_inventory', to='brand.LicenseProfile', verbose_name='License Profile'),
        ),
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]

