# Generated by Django 2.2 on 2021-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0085_custominventory_license_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominventory',
            old_name='books_po_id',
            new_name='po_id',
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='po_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Order id'),
        ),
    ]
