# Generated by Django 2.2 on 2021-05-13 06:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0088_delete_historicalinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.CreateModel(
            name='InventoryItemDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('item_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='item_data')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name')),
                ('zoho_item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zoho Item ID')),
                ('status', models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='pending_for_approval', max_length=255, verbose_name='Status')),
                ('created_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Created by')),
                ('approved_by', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Approved by')),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approved on')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='inventory.Inventory', verbose_name='item')),
            ],
            options={
                'verbose_name': 'Item Delete Request',
                'verbose_name_plural': 'Item Delete Requests',
            },
        ),
    ]
