# Generated by Django 2.2 on 2021-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0089_auto_20210513_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemdelete',
            name='vendor',
        ),
        migrations.AddField(
            model_name='inventoryitemdelete',
            name='cultivar_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cultivar Name'),
        ),
        migrations.AlterField(
            model_name='inventoryitemdelete',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
