# Generated by Django 2.2 on 2021-05-17 06:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_auto_20210513_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mapped_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
