# Generated by Django 2.2 on 2021-05-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_auto_20210513_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItemDelete',
            new_name='InventoryItemDelist',
        ),
        migrations.AlterModelOptions(
            name='inventoryitemdelist',
            options={'verbose_name': 'Item Delist Request', 'verbose_name_plural': 'Item Delist Requests'},
        ),
    ]
