# Generated by Django 2.2 on 2021-05-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_auto_20210517_0802'),
        ('inventory', '0091_inventory_mapped_items'),
    ]

    operations = [
    ]
