# Generated by Django 2.2 on 2021-05-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_merge_20210517_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryByProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Wholesale - Flower', 'Wholesale - Flower'), ('Wholesale - Isolates', 'Wholesale - Isolates'), ('Wholesale - Terpenes', 'Wholesale - Terpenes'), ('Wholesale - Trim', 'Wholesale - Trim'), ('Wholesale - Concentrates', 'Wholesale - Concentrates'), ('Lab Testing', 'Lab Testing'), ('Services', 'Services')], max_length=255, verbose_name='PRODUCT/PARENT CATEGORY')),
                ('total_thc_max', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Max)')),
                ('total_thc_min', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Min)')),
                ('batch_varities', models.IntegerField(blank=True, null=True, verbose_name='Batches')),
                ('average', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Average $/lb')),
                ('total_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total Value $')),
                ('smalls_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Smalls(lbs)')),
                ('tops_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Tops(lbs)')),
                ('total_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total(lbs)')),
                ('trim_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Trim quantity')),
                ('average_thc', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Avg THC')),
                ('daily_aggrigated_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.DailyInventoryAggrigatedSummary')),
            ],
            options={
                'verbose_name': 'Summary by product category',
            },
        ),
    ]
