# Generated by Django 2.2 on 2021-05-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0095_auto_20210519_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name')),
                ('cf_client_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Client Code')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='VendorDailySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_thc_max', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Max)')),
                ('total_thc_min', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total THC(Min)')),
                ('batch_varities', models.IntegerField(blank=True, null=True, verbose_name='Batches')),
                ('average', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Average $/lb')),
                ('total_value', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total Value $')),
                ('smalls_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Smalls(lbs)')),
                ('tops_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Tops(lbs)')),
                ('total_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total(lbs)')),
                ('trim_quantity', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Trim quantity')),
                ('average_thc', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Avg THC')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summary',
            },
        ),
    ]
