# Generated by Django 2.2 on 2021-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_auto_20210521_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='trim_used',
            field=models.FloatField(blank=True, help_text='This field is used to calculate tax for Isolates, Crude Oil and Distillate Oil.', null=True, verbose_name='Trim Used (lbs)'),
        ),
    ]
