# Generated by Django 2.2 on 2021-05-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_custominventory_trim_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='harvest_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Harvest/Manufacturing/Clone Date'),
        ),
    ]
