# Generated by Django 2.2 on 2021-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0099_auto_20210525_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='trim_used_verified',
            field=models.BooleanField(default=False, verbose_name='Trim Used Verified'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='trim_used',
            field=models.FloatField(blank=True, help_text='This field is used to calculate tax for Isolates, Concentrates and Terpenes.', null=True, verbose_name='Trim Used (lbs)'),
        ),
    ]
