# Generated by Django 2.2 on 2021-06-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0100_auto_20210614_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_trim_qty_lbs',
            field=models.FloatField(blank=True, null=True, verbose_name='Trim QTY Used (lbs)'),
        ),
    ]
