# Generated by Django 2.2 on 2021-07-30 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0103_auto_20210621_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
