# Generated by Django 2.2 on 2021-08-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0106_auto_20210804_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='cultivation_type',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Mixed-Light', 'Mixed-Light')], max_length=255, null=True, verbose_name='Cultivation Type'),
        ),
    ]
