# Generated by Django 2.2 on 2021-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0107_custominventory_cultivation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransitorder',
            name='profile_id',
            field=models.IntegerField(unique=True, verbose_name='profile_id'),
        ),
        migrations.AlterUniqueTogether(
            name='intransitorder',
            unique_together=set(),
        ),
    ]
