# Generated by Django 2.2 on 2021-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0108_auto_20210805_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='marketplace_status',
            field=models.CharField(choices=[('Available', 'Available'), ('In-Testing', 'In-Testing'), ('Processing', 'Processing'), ('Flowering', 'Flowering'), ('Vegging', 'Vegging'), ('Cut to Order', 'Cut to Order'), ('Rooting', 'Rooting')], default='In-Testing', max_length=225, verbose_name='Marketplace Status'),
        ),
    ]
