# Generated by Django 2.2 on 2021-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0109_auto_20210810_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominventory',
            name='have_minimum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='custominventory',
            name='minimum_order_quantity',
        ),
        migrations.AddField(
            model_name='custominventory',
            name='clone_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Clone Date'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='clone_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clone Size (inch)'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='days_to_prepare_clones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days To Prepare Clones'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='manufacturing_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Manufacturing Date'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='total_batch_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Batch Output'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='harvest_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Harvest Date'),
        ),
    ]
