# Generated by Django 2.2 on 2021-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0111_auto_20210811_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='clone_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Clone Size (inch)'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='days_to_prepare_clones',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Days To Prepare Clones'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='total_batch_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Batch Output'),
        ),
    ]
