# Generated by Django 2.2 on 2021-08-17 10:14

from django.db import migrations

def forward_func(apps, schema_editor):
    CustomInventory = apps.get_model("inventory", "CustomInventory")
    for item in CustomInventory.objects.all().select_related('cultivar'):
        item.cultivar_name = item.cultivar.cultivar_name
        item.cultivar_crm_id = item.cultivar.cultivar_crm_id
        item.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0116_custominventory_cultivar_name'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
