# Generated by Django 2.2 on 2021-08-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0117_auto_20210817_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_inventory', to='cultivar.Cultivar', verbose_name='Cultivar'),
        ),
    ]
