# Generated by Django 2.2 on 2021-08-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0118_auto_20210817_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='cultivar_type',
            field=models.CharField(blank=True, choices=[('Sativa', 'Sativa'), ('Indica', 'Indica'), ('Hybrid', 'Hybrid')], max_length=255, null=True, verbose_name='Cultivar Type'),
        ),
    ]
