# Generated by Django 2.2 on 2021-08-17 11:40

from django.db import migrations

def forward_func(apps, schema_editor):
    CustomInventory = apps.get_model("inventory", "CustomInventory")
    for item in CustomInventory.objects.all().select_related('cultivar'):
        if item.cultivar:
            item.cultivar_type = item.cultivar.cultivar_type
            item.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0119_custominventory_cultivar_type'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
