# Generated by Django 2.2 on 2021-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0121_auto_20210818_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='mfg_batch_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batch ID'),
        ),
    ]
