# Generated by Django 2.2 on 2021-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0123_auto_20210824_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_batch_qty_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Batch Quantity (g)'),
        ),
    ]
