# Generated by Django 2.2 on 2021-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0124_auto_20210901_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='client_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
