# Generated by Django 2.2 on 2021-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0126_inventory_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cf_vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor Name'),
        ),
    ]
