# Generated by Django 2.2 on 2021-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0128_auto_20211026_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominventory',
            old_name='trim_used_verified',
            new_name='biomass_used_verified',
        ),
        migrations.AddField(
            model_name='custominventory',
            name='biomass_input_g',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='This field is used to calculate tax for Isolates, Concentrates and Terpenes.', max_digits=16, null=True, verbose_name='Raw Material Input (grams)'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='biomass_type',
            field=models.CharField(blank=True, choices=[('Dried Flower', 'Dried Flower'), ('Dried Leaf', 'Dried Leaf'), ('Fresh Plant', 'Fresh Plant')], max_length=50, null=True, verbose_name='Biomass Type'),
        ),
    ]
