# Generated by Django 2.2 on 2021-11-09 11:39
from django.db import migrations

def forward_func(apps, schema_editor):
    from decimal import Decimal
    CustomInventory = apps.get_model("inventory", "CustomInventory")
    for obj in CustomInventory.objects.all():
        if obj.trim_used:
            val = Decimal(str(obj.trim_used)) * Decimal('453.59237')
            obj.biomass_input_g = val.to_eng_string()
            obj.biomass_type = 'Dried Leaf'
            obj.save()

def reverse_func(apps, schema_editor):
    from decimal import Decimal
    CustomInventory = apps.get_model("inventory", "CustomInventory")
    for obj in CustomInventory.objects.filter(biomass_type='Dried Leaf'):
        if obj.biomass_input_g is not None:
            obj.trim_used = round(Decimal(obj.biomass_input_g)/Decimal('453.59237'), 6)
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0129_auto_20211109_1138'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]

