# Generated by Django 2.2 on 2021-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0130_auto_20211109_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominventory',
            name='trim_used',
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='biomass_used_verified',
            field=models.BooleanField(default=False, verbose_name='Biomass Used Verified'),
        ),
    ]
