# Generated by Django 2.2 on 2021-11-10 06:26

import core.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0131_auto_20211109_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='biomass_input_g',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, help_text='This field is used to calculate tax for Isolates, Concentrates and Terpenes.', max_digits=16, null=True, verbose_name='Raw Material Input (grams)'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='total_batch_quantity',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, help_text='This field is used to calculate tax for Isolates, Concentrates and Terpenes.', max_digits=16, null=True, verbose_name='Total Batch Output'),
        ),
    ]
