# Generated by Django 2.2 on 2021-11-10 06:44

import core.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0132_auto_20211110_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventory',
            name='cultivation_tax',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Total Batch Output'),
        ),
        migrations.AddField(
            model_name='custominventory',
            name='mcsp_fee',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Total Batch Output'),
        ),
    ]
