# Generated by Django 2.2 on 2021-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0133_auto_20211110_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='biomass_type',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Dried Flower', 'Dried Flower'), ('Dried Leaf', 'Dried Leaf'), ('Fresh Plant', 'Fresh Plant')], max_length=50, null=True, verbose_name='Biomass Type'),
        ),
    ]
