# Generated by Django 2.2 on 2021-11-10 16:09

import core.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0134_auto_20211110_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='category_name',
            field=models.CharField(choices=[('Flower - Tops', 'Flower - Tops'), ('Flower - Small', 'Flower - Small'), ('Trim', 'Trim'), ('Isolates - CBD', 'Isolates - CBD'), ('Isolates - THC', 'Isolates - THC'), ('Isolates - CBG', 'Isolates - CBG'), ('Isolates - CBN', 'Isolates - CBN'), ('Crude Oil - THC', 'Crude Oil - THC'), ('Crude Oil - CBD', 'Crude Oil - CBD'), ('Distillate Oil - THC', 'Distillate Oil - THC'), ('Distillate Oil - CBD', 'Distillate Oil - CBD'), ('Hash', 'Hash'), ('Shatter', 'Shatter'), ('Sauce', 'Sauce'), ('Crumble', 'Crumble'), ('Kief', 'Kief'), ('Terpenes - Cultivar Specific', 'Terpenes - Cultivar Specific'), ('Terpenes - Cultivar Blended', 'Terpenes - Cultivar Blended'), ('Clones', 'Clones')], max_length=225, verbose_name='Item Category Name'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='cultivation_tax',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Cultivation Tax'),
        ),
        migrations.AlterField(
            model_name='custominventory',
            name='mcsp_fee',
            field=core.db.models.fields.PositiveDecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='MCSP Fee'),
        ),
    ]
