# Generated by Django 2.2 on 2021-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0135_auto_20211110_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='farm_ask_price',
            field=models.FloatField(verbose_name='Farm Ask Price'),
        ),
    ]
