# Generated by Django 2.2 on 2021-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0136_auto_20211110_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_biomass',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Biomass Type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_cultivation_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Cultivation Tax'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_mscp',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='MCSP fee'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cf_raw_material_input_g',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Boimass Input (grams)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cf_batch_qty_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Batch Output (grams)'),
        ),
    ]
