# Generated by Django 2.2 on 2021-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0137_auto_20211111_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='farm_ask_price',
            field=models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Farm Ask Price'),
        ),
    ]
