# Generated by Django 2.2 on 2021-11-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0140_inventory_item_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='qr_box_direct_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='QR direct Box URL'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qr_code_box_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR Code-Box ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_qr_code_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='QR Code-Box URL'),
        ),
    ]
