# Generated by Django 2.2 on 2021-12-07 03:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0142_auto_20211126_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemdelist',
            name='item_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='item_data'),
        ),
        migrations.AlterField(
            model_name='inventoryitemedit',
            name='item_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='item_data'),
        ),
    ]
