# Generated by Django 2.2 on 2022-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0144_auto_20211208_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventory',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('60 Days', '60 Days'), ('21 Days', '21 Days'), ('COD', 'COD')], max_length=50, null=True, verbose_name='Payment Terms'),
        ),
    ]
