# Generated by Django 2.2 on 2022-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0145_auto_20220131_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cf_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
