# Generated by Django 2.2 on 2020-04-03 08:22

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=150, null=True, verbose_name='State')),
                ('date_of_birth', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('zip_code', models.CharField(max_length=20, null=True, verbose_name='Zip code')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Mobile Number')),
                ('legal_business_name', models.CharField(max_length=150, null=True, verbose_name='Legal Business Name')),
                ('business_dba', models.CharField(max_length=150, null=True, verbose_name='Business DBA')),
                ('existing_member', models.BooleanField(default=False, verbose_name='Account Existed')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
