# Generated by Django 2.2.2 on 2019-09-06 11:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190805_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[core.validators.full_domain_validator], verbose_name='Website URL'),
        ),
    ]
