# Generated by Django 2.2.2 on 2019-09-06 13:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190906_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[core.validators.full_domain_validator], verbose_name='Website URL'),
        ),
    ]
