# Generated by Django 2.2 on 2020-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200407_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zoho_contact_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Contact ID'),
        ),
    ]
