# Generated by Django 2.2.2 on 2019-09-06 13:23

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190906_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.CharField(max_length=255, null=True, validators=[core.validators.full_domain_validator], verbose_name='Website URL'),
        ),
    ]
