# Generated by Django 2.2 on 2020-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_membercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercategory',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='membercategory',
            name='user',
        ),
        migrations.AddField(
            model_name='membercategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='member_category', to='user.MemberCategory'),
        ),
    ]
