# Generated by Django 2.2.2 on 2019-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190906_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='Completed Onboarding'),
        ),
    ]
