# Generated by Django 2.2.2 on 2019-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_completed_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_hs_deal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HS Deal ID'),
        ),
    ]
