# Generated by Django 2.2 on 2020-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200407_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercategory',
            name='name',
            field=models.CharField(default='cultivator', max_length=255),
            preserve_default=False,
        ),
    ]
