# Generated by Django 2.2.2 on 2019-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_associated_hs_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tour',
            field=models.BooleanField(default=False, verbose_name='Completed Tour'),
        ),
    ]
