# Generated by Django 2.2 on 2020-04-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200421_0544'),
        ('user', '0011_auto_20200421_0712'),
    ]

    operations = [
    ]
