# Generated by Django 2.2 on 2020-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20200421_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Updated In CRM'),
        ),
    ]
