# Generated by Django 2.2 on 2020-05-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200425_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Photo Link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('done', 'Done')], default=None, max_length=20, null=True),
        ),
    ]
