# Generated by Django 2.2 on 2020-05-17 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200514_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved on'),
        ),
    ]
