# Generated by Django 2.2 on 2020-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200523_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('done', 'Done')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='step',
            field=models.CharField(default='0', max_length=255, verbose_name='Steps'),
        ),
    ]
