# Generated by Django 2.2 on 2020-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200528_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(choices=[('business', 'Business'), ('personal', 'Personal')], default='business', max_length=60, verbose_name='Membership Type'),
            preserve_default=False,
        ),
    ]
