# Generated by Django 2.2 on 2020-09-24 11:22

from django.db import migrations, models
import phonenumber_field.modelfields
import utils.otp


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200908_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Is Phone Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=utils.otp.random_hex_str, help_text='Hex-encoded secret key', max_length=40, validators=[utils.otp.key_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone'),
        ),
    ]
