# Generated by Django 2.2 on 2020-10-13 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import two_factor.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, editable=False, verbose_name='is Two Factor Enabled'),
        ),
        migrations.CreateModel(
            name='PrimaryPhoneTOTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.')),
                ('name', models.CharField(blank=True, default='', help_text='The human-readable name of this device.', max_length=64)),
                ('key', models.CharField(default=two_factor.utils.random_hex, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[two_factor.utils.key_validator])),
                ('token_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp of the token generation.')),
                ('event_code', models.CharField(default='', max_length=255, verbose_name='Event Code String')),
                ('user', models.OneToOneField(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='primary_phone_totp_device', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Primary Phone TOTP Device',
                'verbose_name_plural': 'Primary Phone Totp Devices',
            },
        ),
    ]
