# Generated by Django 2.2 on 2020-10-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20201013_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryphonetotpdevice',
            name='name',
        ),
    ]
