# Generated by Django 2.2 on 2020-10-20 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_primaryphonetotpdevice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryphonetotpdevice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primaryphonetotpdevice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
