# Generated by Django 2.2 on 2020-10-27 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20201023_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='legal_business_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
