# Generated by Django 2.2 on 2020-11-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20201104_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditionAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile_type', models.CharField(max_length=255, verbose_name='IP Address')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(max_length=1000, verbose_name='user_agent')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_condition_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Terms And Condition Acceptance',
                'verbose_name_plural': 'Terms And Condition Acceptances',
            },
        ),
    ]
