# Generated by Django 2.2 on 2020-11-09 11:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20201106_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile_type', models.CharField(max_length=255, verbose_name='Profile Type')),
                ('terms_and_condition', ckeditor.fields.RichTextField(verbose_name='Terms And Condition')),
                ('publish_from', models.DateField(verbose_name='Publish From')),
            ],
            options={
                'verbose_name': 'Terms And Condition',
            },
        ),
        migrations.RemoveField(
            model_name='termsandconditionacceptance',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='termsandconditionacceptance',
            name='is_accepted',
            field=models.BooleanField(default=True, verbose_name='Is Accepted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsandconditionacceptance',
            name='terms_and_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_and_condition_acceptances', to='user.TermsAndCondition', verbose_name='Terms And Condition'),
            preserve_default=False,
        ),
    ]
