# Generated by Django 2.2 on 2020-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20201109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='profile_type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer'), ('other', 'other')], max_length=255, verbose_name='Profile Type'),
        ),
    ]
