# Generated by Django 2.2 on 2020-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20201110_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='profile_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('other', 'Other')], max_length=255, verbose_name='Profile Type'),
        ),
    ]
