# Generated by Django 2.2 on 2020-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20201111_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM link'),
        ),
    ]
