# Generated by Django 2.2 on 2020-12-10 18:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_user_crm_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('page', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Terms And Condition')),
            ],
            options={
                'verbose_name': 'Help Documentation',
            },
        ),
    ]
