# Generated by Django 2.2 on 2020-12-14 09:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_helpdocumentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdocumentation',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
