# Generated by Django 2.2 on 2020-12-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20201214_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpdocumentation',
            old_name='page',
            new_name='for_page',
        ),
    ]
