# Generated by Django 2.2 on 2020-12-16 11:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20201214_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdocumentation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
