# Generated by Django 2.2 on 2020-12-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20201216_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdocumentation',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordering'),
        ),
    ]
