# Generated by Django 2.2 on 2021-03-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_user_bypass_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='zoho CRM Id'),
        ),
    ]
