# Generated by Django 2.2 on 2021-04-08 13:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_user_zoho_crm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(default=user.models.generate_unique_user_id, max_length=255, null=True, verbose_name='Unique User Id'),
        ),
    ]
