# Generated by Django 2.2 on 2021-05-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0071_nurseryoverview'),
        ('user', '0050_auto_20210408_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.Organization', verbose_name='Default Organization Id'),
        ),
    ]
