# Generated by Django 2.2 on 2021-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(related_name='member_category', to='user.MemberCategory', verbose_name='Member Categories'),
        ),
    ]
