# Generated by Django 2.2 on 2022-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20210723_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recive_cart_notification',
            field=models.BooleanField(default=False, verbose_name='Recive Cart Notification'),
        ),
    ]
