# Generated by Django 2.2 on 2022-03-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_user_recive_cart_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recive_cart_notification',
            new_name='receive_cart_notification',
        ),
    ]
