# Generated by Django 2.2 on 2022-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20220322_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_cart_notification',
            field=models.BooleanField(default=False, verbose_name='Receive Cart Notification'),
        ),
    ]
