# Generated by Django 2.2 on 2022-03-25 07:18

import core.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_auto_20220322_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.db.models.fields.CaseInsensitiveEmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
