# Generated by Django 2.2 on 2021-04-20 04:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('estimate_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimate ID')),
                ('estimate_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimate Number')),
                ('organization', models.CharField(choices=[('EFD', 'efd'), ('EFL', 'efl'), ('EFN', 'efn')], default='efd', max_length=255, verbose_name='Organization')),
                ('estimate_date', models.DateField(default=None)),
                ('status', models.CharField(default='draft', max_length=255, verbose_name='Status')),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('currency_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency ID')),
                ('currency_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency Code')),
                ('discount', models.FloatField(default=0.0, verbose_name='Discount')),
                ('is_discount_before_tax', models.BooleanField(default=False, verbose_name='Is Discount Before Tax')),
                ('is_inclusive_tax', models.BooleanField(default=False, verbose_name='Is Inclusive Tax')),
                ('estimate_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Estimate URL')),
                ('shipping_charge', models.FloatField(default=0.0, verbose_name='Shipping Charge')),
                ('roundoff_value', models.FloatField(default=0.0, verbose_name='RoundOff Value')),
                ('sub_total', models.FloatField(verbose_name='Subtotal')),
                ('sub_total_inclusive_of_tax', models.FloatField(blank=True, null=True, verbose_name='Subtotal')),
                ('total', models.FloatField(verbose_name='Total')),
                ('tax_total', models.FloatField(blank=True, null=True, verbose_name='Tax Total')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('terms', models.CharField(blank=True, max_length=255, null=True, verbose_name='Terms')),
                ('custom_fields', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, null=True, size=None)),
                ('contact_persons_details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('salesperson_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesperson ID')),
                ('salesperson_name', models.CharField(max_length=255, verbose_name='Salesperson Name')),
                ('payment_options', models.CharField(max_length=255, verbose_name='Payment Options')),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request ID')),
            ],
            options={
                'verbose_name': 'estimate',
                'verbose_name_plural': 'estimates',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item_id', models.CharField(max_length=255, verbose_name='item_id')),
                ('sku', models.CharField(max_length=255, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('item_order', models.CharField(max_length=255, verbose_name='Item Order')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('discount_amount', models.FloatField(default=0.0, verbose_name='Discount Amount')),
                ('discount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount')),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax ID')),
                ('tax_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Name')),
                ('tax_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tax Type')),
                ('tax_percentage', models.FloatField(blank=True, null=True, verbose_name='Tax Percentage')),
                ('item_total', models.FloatField(verbose_name='Total')),
                ('item_custom_fields', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, null=True, size=None)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='bill.Estimate', verbose_name='Estimate')),
            ],
            options={
                'verbose_name': 'lineitem',
                'verbose_name_plural': 'lineitems',
            },
        ),
    ]
