# Generated by Django 2.2 on 2021-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_date',
            field=models.DateField(auto_now=True),
        ),
    ]
