# Generated by Django 2.2 on 2021-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20210420_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Terms'),
        ),
    ]
