# Generated by Django 2.2 on 2021-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20210420_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
