# Generated by Django 2.2 on 2021-05-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_estimate_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name': 'Pending Orders', 'verbose_name_plural': 'Pending Orders'},
        ),
        migrations.AlterModelOptions(
            name='lineitem',
            options={'verbose_name': 'Line Item/Inventory Item', 'verbose_name_plural': 'Line Items/Inventory Items'},
        ),
    ]
