# Generated by Django 2.2 on 2021-09-21 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20210505_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='contact_persons_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='payment_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Options'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='salesperson_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesperson Name'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='item_id'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_order',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Order'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
