BILLS_FORMAT = {
    'estimate':{
        'id': 'id',
        'estimate_id': 'estimate_id',
        'estimate_number': 'estimate_number',
        'organization': 'organization',
        'estimate_date': 'estimate_date',
        'status': 'status',
        'customer_id': 'customer_id',
        'customer_name': 'customer_name',
        'currency_id': 'currency_id',
        'currency_code': 'currency_code',
        'discount': 'discount',
        'is_discount_before_tax': 'is_discount_before_tax',
        'is_inclusive_tax': 'is_inclusive_tax',
        'estimate_url': 'estimate_url',
        'shipping_charge': 'shipping_charge',
        'roundoff_value': 'roundoff_value',
        'sub_total': 'sub_total',
        'sub_total_inclusive_of_tax': 'sub_total_inclusive_of_tax',
        'total': 'total',
        'tax_total': 'tax_total',
        'billing_address': 'billing_address',
        'shipping_address': 'shipping_address',
        'notes': 'notes',
        'terms': 'terms',
        'custom_fields': 'custom_fields',
        'contact_persons_details': 'contact_persons_details',
        'salesperson_id': 'salesperson_id',
        'salesperson_name': 'salesperson_name',
        'payment_options': 'payment_options',
        'request_id': 'request_id',
        'description': 'description'
 },
    'item':{
        'id': 'id',
        'estimate_id': 'estimate_id',
        'item_id': 'item_id',
        'sku': 'sku',
        'name': 'name',
        'description': 'description',
        'item_order': 'item_order',
        'rate': 'rate',
        'quantity': 'quantity',
        'unit': 'unit',
        'discount_amount': 'discount_amount',
        'discount': 'discount',
        'tax_id': 'tax_id',
        'tax_name': 'tax_name',
        'tax_type': 'tax_type',
        'tax_percentage': 'tax_percentage',
        'item_total': 'item_total',
        'item_custom_fields': 'item_custom_fields'}
}