# Generated by Django 2.2 on 2021-05-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0072_auto_20210512_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinderLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('crop_overview', 'Crop Overview'), ('financial_overview', 'Financial Overview'), ('expired', 'Expired'), ('done', 'Done')], default='not_started', max_length=20)),
                ('step', models.CharField(default='0', max_length=255, verbose_name='Steps')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=255, verbose_name='License Number')),
                ('legal_business_name', models.CharField(max_length=255, verbose_name='Legal Business Name')),
                ('license_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='License Type')),
                ('profile_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Category')),
                ('premises_address', models.TextField(blank=True, null=True)),
                ('premises_county', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises County')),
                ('premises_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises City')),
                ('premises_apn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises APN')),
                ('premises_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises State')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises Zip')),
                ('issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expiration Date')),
                ('uploaded_license_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded To')),
                ('uploaded_sellers_permit_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded Sellers Permit To')),
                ('uploaded_w9_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded W9  To')),
                ('is_updated_in_crm', models.BooleanField(default=False, verbose_name='Is Updated In CRM')),
                ('zoho_crm_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID')),
                ('zoho_books_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Books ID')),
                ('status_before_expiry', models.CharField(blank=True, max_length=100, null=True, verbose_name='License status before expiry')),
                ('profile_license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.License', verbose_name='Profile License')),
            ],
            options={
                'verbose_name': 'License',
            },
        ),
    ]
