# Generated by Django 2.2 on 2021-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_binder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binderlicense',
            name='is_updated_in_crm',
        ),
        migrations.RemoveField(
            model_name='binderlicense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='binderlicense',
            name='step',
        ),
        migrations.RemoveField(
            model_name='binderlicense',
            name='zoho_books_id',
        ),
        migrations.AddField(
            model_name='binderlicense',
            name='is_updated_via_trigger',
            field=models.BooleanField(default=False, verbose_name='Is Updated Via Trigger'),
        ),
        migrations.AddField(
            model_name='binderlicense',
            name='license_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('About to Expire', 'About to Expire'), ('Expired', 'Expired'), ('Expired - Pending Renewal', 'Expired - Pending Renewal'), ('Inactive', 'Inactive'), ('Revoked', 'Revoked'), ('Surrendered', 'Surrendered'), ('Suspended', 'Suspended')], max_length=50, null=True),
        ),
    ]
