# Generated by Django 2.2 on 2021-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_binder', '0002_auto_20210521_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binderlicense',
            name='status_before_expiry',
        ),
        migrations.AlterField(
            model_name='binderlicense',
            name='license_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('About to Expire', 'About to Expire'), ('Expired', 'Expired'), ('Expired - Pending Renewal', 'Expired - Pending Renewal'), ('Inactive', 'Inactive'), ('Revoked', 'Revoked'), ('Surrendered', 'Surrendered'), ('Suspended', 'Suspended')], max_length=255, null=True),
        ),
    ]
