# Generated by Django 2.2 on 2020-10-15 10:20

from django.conf import settings
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetotpdevice',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone'),
        ),
        migrations.AlterUniqueTogether(
            name='phonetotpdevice',
            unique_together={('user', 'phone_number')},
        ),
    ]
