# Generated by Django 2.2 on 2020-10-19 08:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import two_factor.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0002_auto_20201015_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetotpdevice',
            name='name',
        ),
        migrations.CreateModel(
            name='AuthySoftTOTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, help_text='Is this device ready for use?')),
                ('name', models.CharField(default='Authy Soft Token', max_length=255)),
                ('authy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authy_soft_totp_devices', to='two_factor.AuthyUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authy_soft_totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authy Soft TOTP Device',
                'verbose_name_plural': 'Authy Soft TOTP Devices',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddAuthenticatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, default=two_factor.utils.random_hex_32, max_length=128, validators=[two_factor.utils.key_validator], verbose_name='Request Id')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued At')),
                ('is_completed', models.BooleanField(default=False)),
                ('devices_data', django.contrib.postgres.fields.jsonb.JSONField(default=list, editable=False, verbose_name='Devices Data')),
                ('user', models.OneToOneField(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='add_authenticator_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add Authenticator Request',
                'verbose_name_plural': 'Add Authenticator Requests',
            },
        ),
    ]
