# Generated by Django 2.2 on 2021-07-05 05:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origin')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path')),
                ('deleted_objects', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Deleted Objects')),
                ('created_objects', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Created Objects')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversion_meta', to='reversion.Revision')),
            ],
        ),
        migrations.CreateModel(
            name='OldVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text='The serialization format used by this model.', max_length=255)),
                ('serialized_data', models.TextField(help_text='The serialized form of prev instance of the model.')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_version', to='reversion.Version')),
            ],
        ),
    ]
