# Generated by Django 2.2 on 2020-05-17 22:00

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('done', 'Done')], default=None, max_length=20, null=True)),
                ('step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Steps')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name')),
                ('account_category', models.CharField(choices=[('cultivator', 'Cultivator'), ('distributor', 'Distributor'), ('manufacturer', 'Manufacturer'), ('retailer', 'Retailer')], max_length=60, verbose_name='Account Category')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True, verbose_name='Approved on')),
                ('approved_by', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Approved by')),
                ('ac_manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manages_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Account Manager')),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
        migrations.CreateModel(
            name='AccountLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='License Type')),
                ('owner_or_manager', models.CharField(blank=True, max_length=12, null=True, verbose_name='Owner or Manager')),
                ('legal_business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Business Name')),
                ('license_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='License Number')),
                ('expiration_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expiration Date')),
                ('issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='Issue Date')),
                ('premises_address', models.TextField()),
                ('premises_county', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises County')),
                ('premises_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises City')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises Zip')),
                ('premises_apn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises APN')),
                ('premises_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Premises State')),
                ('uploaded_license_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded To')),
                ('uploaded_sellers_permit_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded Sellers Permit To')),
                ('uploaded_w9_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Uploaded W9  To')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Is Draft')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Phone')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('company_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compony Email')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Name')),
                ('owner_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Email')),
                ('owner_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner Phone')),
                ('logistic_manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logistic Manager Name')),
                ('logistic_manager_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logistic Manager Email')),
                ('logistic_manager_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logistic Manager Phone')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('linked_in', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linked In')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook')),
                ('billing_compony_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Nompony Name')),
                ('billing_street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Street')),
                ('billing_street_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Street Line 2')),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing City')),
                ('billing_zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Zip Code')),
                ('billing_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Zip Code')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Is Draft')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_contact', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountBasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('preferred_payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Preferred Payment')),
                ('cultivars_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('ethics_and_certification', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('product_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('provide_transport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provide Transport')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Is Draft')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to='account.Account')),
            ],
        ),
    ]
