# Generated by Django 2.2 on 2020-05-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Updated In CRM'),
        ),
        migrations.AddField(
            model_name='account',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID'),
        ),
        migrations.AlterField(
            model_name='accountlicense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_license', to='account.Account'),
        ),
    ]
