# Generated by Django 2.2 on 2020-05-19 09:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200518_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_compony_name',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_street_line_2',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='billing_zip_code',
        ),
        migrations.AddField(
            model_name='accountcontactinfo',
            name='billing_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='accountcontactinfo',
            name='mailing_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
