# Generated by Django 2.2 on 2020-05-19 11:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200519_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='approved_by',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Approved by'),
        ),
    ]
