# Generated by Django 2.2 on 2020-05-19 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200519_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcontactinfo',
            name='billing_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontactinfo',
            name='mailing_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
