# Generated by Django 2.2 on 2020-05-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200519_1123'),
        ('account', '0002_auto_20200518_0516'),
    ]

    operations = [
    ]
