# Generated by Django 2.2 on 2020-05-21 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_merge_20200520_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales/Inventory Email'),
        ),
        migrations.AddField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales/inventory Name'),
        ),
        migrations.AddField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales/Inventory Phone'),
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('logistics', 'logistics'), ('sales_or_inventory', 'sales_or_inventory')], max_length=60, verbose_name='Role')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to='account.Account', verbose_name='Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('account', 'user')},
            },
        ),
    ]
