# Generated by Django 2.2 on 2020-05-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200521_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('license_owner', 'License Owner'), ('logistics', 'Logistics'), ('sales_or_inventory', 'Sales or Inventory')], max_length=60, verbose_name='Role'),
        ),
    ]
