# Generated by Django 2.2 on 2020-06-05 10:36

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200523_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='logistic_manager_email',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='logistic_manager_name',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='logistic_manager_phone',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_email',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_name',
        ),
        migrations.RemoveField(
            model_name='accountcontactinfo',
            name='sales_or_inventory_phone',
        ),
        migrations.AddField(
            model_name='accountcontactinfo',
            name='employees',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), default=list, size=None),
        ),
    ]
