# Generated by Django 2.2 on 2020-06-20 07:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200605_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number_of_legal_entities',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='number_of_licenses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
