# Generated by Django 2.2 on 2020-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200620_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
            },
        ),
        migrations.AddField(
            model_name='accountbasicprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand Name'),
        ),
    ]
