# Generated by Django 2.2 on 2020-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200722_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountCategory',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('manufacturing', 'Manufacturing'), ('retail', (('storefront', 'Storefront'), ('delivery', 'Delivery')))], max_length=60, verbose_name='Account Category'),
        ),
    ]
