# Generated by Django 2.2 on 2020-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200723_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('manufacturing', 'Manufacturing'), ('Retail', (('storefront', 'Storefront'), ('delivery', 'Delivery')))], max_length=60, verbose_name='Account Category'),
        ),
    ]
