# Generated by Django 2.2 on 2021-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('page_url', models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Page URL')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page Name')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page Title')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Page Meta',
            },
        ),
    ]
