# Generated by Django 2.2 on 2021-02-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_internalrole_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalrole',
            name='users',
        ),
    ]
