# Generated by Django 2.2 on 2021-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0065_auto_20210225_0810'),
        ('permission', '0003_remove_internalrole_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalrole',
            name='profile_categories',
            field=models.ManyToManyField(blank=True, to='brand.ProfileCategory', verbose_name='Profile Categories'),
        ),
    ]
