# Generated by Django 2.2 on 2021-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_internalrole_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalrole',
            name='created_profiles_only',
            field=models.BooleanField(default=True, verbose_name='Created Profiles Only'),
        ),
    ]
