# Generated by Django 2.2 on 2021-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_internalrole_created_profiles_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalrole',
            name='created_profiles_only',
            field=models.BooleanField(default=True, verbose_name='Owned Profiles Only'),
        ),
    ]
