# Generated by Django 2.2 on 2021-03-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20210318_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalrole',
            old_name='created_profiles_only',
            new_name='owned_profiles_only',
        ),
    ]
