# Generated by Django 2.2 on 2021-03-22 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission', '0007_auto_20210318_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalrole',
            name='role_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Role Users'),
        ),
    ]
