# Generated by Django 2.2 on 2020-06-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='modify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
