# Generated by Django 2.2 on 2021-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0002_auto_20200603_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='status',
            field=models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='approved', max_length=255, verbose_name='Status'),
        ),
    ]
