# Generated by Django 2.2 on 2021-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0003_cultivar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='status',
            field=models.CharField(choices=[('pending_for_approval', 'Pending For Approval'), ('approved', 'Approved')], default='pending_for_approval', max_length=255, verbose_name='Status'),
        ),
    ]
