# Generated by Django 2.2 on 2021-02-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0004_auto_20210122_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='terpenes_primary',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='terpenes_secondary',
        ),
    ]
