# Generated by Django 2.2 on 2021-02-08 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0005_auto_20210208_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='effect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='flavor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='terpenes_primary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='terpenes_secondary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
