# Generated by Django 2.2 on 2021-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0006_auto_20210208_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='cbd_range_high',
            field=models.FloatField(blank=True, null=True, verbose_name='CBD HIGH'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='cbd_range_low',
            field=models.FloatField(blank=True, null=True, verbose_name='CBD LOW'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='cbg_range_high',
            field=models.FloatField(blank=True, null=True, verbose_name='CBG HIGH'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='cbg_range_low',
            field=models.FloatField(blank=True, null=True, verbose_name='CBG LOW'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='thc_range_high',
            field=models.FloatField(blank=True, null=True, verbose_name='THC HIGH'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='thc_range_low',
            field=models.FloatField(blank=True, null=True, verbose_name='THC LOW'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='thcv_range_high',
            field=models.FloatField(blank=True, null=True, verbose_name='THCv HIGH'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='thcv_range_low',
            field=models.FloatField(blank=True, null=True, verbose_name='THCv LOW'),
        ),
    ]
