# Generated by Django 2.2 on 2021-08-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0009_auto_20210816_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='cultivar_type',
            field=models.CharField(blank=True, choices=[('Sativa', 'Sativa'), ('Indica', 'Indica'), ('Hybrid', 'Hybrid'), ('Hybrid - Indica Dominant', 'Hybrid - Indica Dominant'), ('Hybrid - Sativa Dominant', 'Hybrid - Sativa Dominant')], max_length=50, null=True, verbose_name='Cultivar Type'),
        ),
    ]
