# Generated by Django 2.2 on 2020-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivationoverview',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is Draft'),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('done', 'Done')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='license',
            name='step',
            field=models.CharField(default='0', max_length=255, verbose_name='Steps'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Is Draft'),
        ),
    ]
