# Generated by Django 2.2 on 2020-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20200905_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='premises_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
