# Generated by Django 2.2 on 2020-09-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20200907_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseprofile',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_profile', to='brand.License', verbose_name='LicenseProfile'),
        ),
    ]
