# Generated by Django 2.2 on 2020-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20200907_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'LicenseProfile'},
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('crop_overview', 'Crop Overview'), ('financial_overview', 'Financial Overview'), ('done', 'Done')], default='not_started', max_length=20),
        ),
    ]
