# Generated by Django 2.2 on 2020-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20200908_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Updated In CRM'),
        ),
        migrations.AddField(
            model_name='brand',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID'),
        ),
        migrations.AddField(
            model_name='license',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Updated In CRM'),
        ),
        migrations.AddField(
            model_name='license',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Updated In CRM'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID'),
        ),
    ]
