# Generated by Django 2.2 on 2020-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20200908_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='profile_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Category Individual user'),
        ),
    ]
