# Generated by Django 2.2 on 2020-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_auto_20200909_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='farm_photo_sharable_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Farm Profile Photo Sharable Link'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='farm_profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Farm Profile Photo Box ID'),
        ),
    ]
