# Generated by Django 2.2 on 2020-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20200909_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='featured_on_our_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='have_marketing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='interested_in_co_branding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropoverview',
            name='need_processing_support',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropoverview',
            name='process_on_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='issues_with_failed_labtest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='other_distributors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='transportation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
