# Generated by Django 2.2 on 2020-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_auto_20200909_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
    ]
