# Generated by Django 2.2 on 2020-09-10 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_brand_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationoverview',
            name='type_of_nutrients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='transportation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
