# Generated by Django 2.2 on 2020-09-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20200910_0510'),
        ('brand', '0012_auto_20200911_0517'),
    ]

    operations = [
    ]
