# Generated by Django 2.2 on 2020-09-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_merge_20200911_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='profile_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profile Category'),
        ),
    ]
