# Generated by Django 2.2 on 2020-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_auto_20200911_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseprofile',
            name='farm_county',
        ),
        migrations.RemoveField(
            model_name='licenseprofile',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
