# Generated by Django 2.2 on 2020-09-14 05:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0016_auto_20200911_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropoverview',
            name='indoor',
        ),
        migrations.RemoveField(
            model_name='cropoverview',
            name='mixed_light',
        ),
        migrations.RemoveField(
            model_name='cropoverview',
            name='outdoor_autoflower',
        ),
        migrations.RemoveField(
            model_name='cropoverview',
            name='outdoor_full_season',
        ),
        migrations.RemoveField(
            model_name='cultivationoverview',
            name='indoor',
        ),
        migrations.RemoveField(
            model_name='cultivationoverview',
            name='mixed_light',
        ),
        migrations.RemoveField(
            model_name='cultivationoverview',
            name='outdoor_autoflower',
        ),
        migrations.RemoveField(
            model_name='cultivationoverview',
            name='outdoor_full_season',
        ),
        migrations.RemoveField(
            model_name='financialoverview',
            name='indoor',
        ),
        migrations.RemoveField(
            model_name='financialoverview',
            name='mixed_light',
        ),
        migrations.RemoveField(
            model_name='financialoverview',
            name='outdoor_autoflower',
        ),
        migrations.RemoveField(
            model_name='financialoverview',
            name='outdoor_full_season',
        ),
        migrations.AddField(
            model_name='cropoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), default=list, size=None),
        ),
        migrations.AddField(
            model_name='cultivationoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financialoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(default=dict), default=list, size=None),
        ),
    ]
