# Generated by Django 2.2 on 2020-09-15 09:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0018_auto_20200915_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cultivationoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialoverview',
            name='overview',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
