# Generated by Django 2.2 on 2020-09-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0020_profilereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Report Manager'),
        ),
    ]
