# Generated by Django 2.2 on 2020-09-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0021_auto_20200918_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'License/Profile'},
        ),
    ]
