# Generated by Django 2.2 on 2020-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0023_auto_20200930_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='lab_test_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
