# Generated by Django 2.2 on 2020-10-19 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0024_licenseprofile_lab_test_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
