# Generated by Django 2.2 on 2020-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0026_auto_20201104_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Brand Name'),
        ),
    ]
