# Generated by Django 2.2 on 2020-11-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0028_license_is_data_fetching_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='zoho_books_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Books ID'),
        ),
        migrations.AddField(
            model_name='license',
            name='zoho_books_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Books ID'),
        ),
    ]
