# Generated by Django 2.2 on 2020-11-10 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0029_auto_20201106_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseuser',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('owner', 'Owner'), ('license_owner', 'License Owner'), ('farm_manager', 'Farm Manager'), ('logistics', 'Logistics'), ('sales_or_inventory', 'Sales or Inventory'), ('billing', 'Billing')], help_text='choice options are 1.license_owner 2.farm_manager 3.logistics 4.sales_or_inventory 5.billing', max_length=60, verbose_name='Role'), size=None),
        ),
    ]
