# Generated by Django 2.2 on 2020-11-17 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0031_auto_20201117_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_roles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
