# Generated by Django 2.2 on 2020-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0032_auto_20201117_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='status_before_expiry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='License status before expiry'),
        ),
    ]
