# Generated by Django 2.2 on 2020-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0033_license_status_before_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_updated_via_trigger',
            field=models.BooleanField(default=False, verbose_name='Is Updated Via Trigger'),
        ),
    ]
