# Generated by Django 2.2 on 2020-11-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_organization(apps, schema_editor):
    User = apps.get_model("user", "User")
    Organization = apps.get_model("brand", "Organization")
    for user in User.objects.all():
        Organization.objects.get_or_create(
            name='My Organization',
            created_by=user,
        )

def create_organization_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0033_license_status_before_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.RunPython(create_organization, reverse_code=create_organization_reverse),
    ]
