# Generated by Django 2.2 on 2020-11-27 07:53
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def Add_license_organization(apps, schema_editor):
    License = apps.get_model("brand", "License")
    Organization = apps.get_model("brand", "Organization")
    for license in License.objects.all():
        organization, _ = Organization.objects.get_or_create(
            name='My Organization',
            created_by=license.created_by,
        )
        license.organization = organization
        license.save()

def Add_license_organization_reverse(apps, schema_editor):
    # pass
    License = apps.get_model("brand", "License")
    Organization = apps.get_model("brand", "Organization")
    for license in License.objects.all():
        organization = Organization.objects.get(id=license.organization_id)
        license.created_by_id = organization.created_by_id
        license.save()

class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0034_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='brand.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='license',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.RunPython(Add_license_organization, reverse_code=Add_license_organization_reverse),
        migrations.AlterField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='brand.Organization', verbose_name='Organization'),
        ),
        migrations.RemoveField(
            model_name='license',
            name='created_by',
        ),
    ]
