# Generated by Django 2.2 on 2020-11-27 10:44

from django.db import migrations, models
import django.db.models.deletion


def Add_brand_organization(apps, schema_editor):
    Brand = apps.get_model("brand", "Brand")
    License = apps.get_model("brand", "License")
    Organization = apps.get_model("brand", "Organization")
    for brand in Brand.objects.all():
        if brand.ac_manager_id:
            organization, _ = Organization.objects.get_or_create(
                name='My Organization',
                created_by=brand.ac_manager,
            )
            brand.organization = organization
            brand.save()
        else:
            license = License.objects.filter(brand=brand).first()
            if license:
                brand.organization_id = license.organization_id
                brand.save()


def Add_brand_organization_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0035_license_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='brand.Organization', verbose_name='Organization'),
        ),
        migrations.RunPython(Add_brand_organization, reverse_code=Add_brand_organization_reverse),
        migrations.RemoveField(
            model_name='brand',
            name='parent_brand',
        ),
    ]
