# Generated by Django 2.2 on 2020-12-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0036_brand_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='ac_manager',
        ),
        migrations.AlterField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='brand.Organization', verbose_name='Organization'),
        ),
    ]
