# Generated by Django 2.2 on 2020-12-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0040_auto_20201215_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='codename')),
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('group__name', 'codename'), 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='permission',
            name='displayname',
            field=models.CharField(default='', max_length=100, verbose_name='displayname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='brand.PermissionGroup', verbose_name='Group'),
        ),
    ]
