# Generated by Django 2.2 on 2020-12-28 06:32

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0042_organizationuserinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ethics_and_certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, verbose_name='Ethics And Certifications'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organizationuserinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 6, 32, 27, 191523, tzinfo=utc)),
        ),
    ]
