# Generated by Django 2.2 on 2020-12-28 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0043_auto_20201228_0632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenserolepermissions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='licenserolepermissions',
            name='license',
        ),
        migrations.RemoveField(
            model_name='licenserolepermissions',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='licenserolepermissions',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='licenseuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='licenseuser',
            name='license',
        ),
        migrations.RemoveField(
            model_name='licenseuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='licenseuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='organizationuserinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 10, 22, 57, 961983, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LicenseRole',
        ),
        migrations.DeleteModel(
            name='LicenseRolePermissions',
        ),
        migrations.DeleteModel(
            name='LicenseUser',
        ),
    ]
