# Generated by Django 2.2 on 2020-12-28 14:30

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0044_auto_20201228_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuserinvite',
            name='expires_at',
            field=models.DateTimeField(default=brand.models.get_invite_expiration_time),
        ),
    ]
