# Generated by Django 2.2 on 2020-12-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0045_auto_20201228_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationrole',
            name='permissions',
        ),
    ]
