# Generated by Django 2.2 on 2020-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0046_remove_organizationrole_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='codename'),
        ),
    ]
