# Generated by Django 2.2 on 2020-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0047_auto_20201229_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='brand.Permission', verbose_name='Permissions'),
        ),
    ]
