# Generated by Django 2.2 on 2020-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0048_organizationrole_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('group__name', 'id'), 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='codename',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='displayname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
