# Generated by Django 2.2 on 2020-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0049_auto_20201229_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationuserinvite',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='organizationuserinvite',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='organizationuserinvite',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='organizationuserinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=60),
        ),
    ]
