# Generated by Django 2.2 on 2021-01-05 06:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0050_auto_20201230_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None)),
                ('routing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Routing')),
                ('checking', models.CharField(blank=True, max_length=255, null=True, verbose_name='Checking')),
                ('bank_address', models.TextField(blank=True, null=True, verbose_name='Bank Address')),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_information', to='brand.License', verbose_name='License')),
            ],
        ),
    ]
