# Generated by Django 2.2 on 2021-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0051_billinginformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand Image'),
        ),
    ]
