# Generated by Django 2.2 on 2021-01-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0052_brand_brand_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginformation',
            old_name='checking',
            new_name='bank_account_number',
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.RenameField(
            model_name='billinginformation',
            old_name='routing',
            new_name='bank_routing_number',
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Routing Number'),
        ),
        migrations.RemoveField(
            model_name='billinginformation',
            name='bank_address',
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='bank_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank City'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='bank_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Street'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='bank_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Zip Code '),
        ),
    ]
