# Generated by Django 2.2 on 2021-01-12 17:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import two_factor.utils


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0054_remove_brand_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDataFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.')),
                ('data_fetch_token', models.CharField(db_index=True, default=two_factor.utils.random_hex_32, max_length=128, unique=True, validators=[two_factor.utils.key_validator])),
                ('license_number', models.CharField(max_length=255, verbose_name='License Number')),
                ('legal_business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Business Name')),
                ('owner_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Owner Email')),
                ('owner_name', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Owner Email')),
                ('crm_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='CRM Data')),
                ('last_otp_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Token Time')),
                ('key', models.CharField(default=two_factor.utils.random_hex, max_length=80, validators=[two_factor.utils.key_validator])),
                ('counter', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('licence_data_not_found', 'Licence Data Not Found'), ('owner_email_not_found', 'Owner Email Not Found'), ('owner_verification_sent', 'Owner Verification Sent'), ('verified', 'Verified'), ('inserting', 'Inserting'), ('complete', 'Complete')], default='not_started', max_length=255, verbose_name='Data From CRM Status')),
            ],
            options={
                'verbose_name': 'Owner Verification HOTP Device',
                'abstract': False,
            },
        ),
    ]
