# Generated by Django 2.2 on 2021-01-13 04:46

import django.contrib.postgres.fields
from django.db import migrations, models

def preferred_payment_to_array(apps, schema_editor):
    LicenseProfile = apps.get_model("brand", "LicenseProfile")
    for profile in LicenseProfile.objects.all():
        if profile.preferred_payment:
            if isinstance(profile.preferred_payment, str):
                profile.preferred_payments = [profile.preferred_payment,]
                profile.save()
            elif isinstance(profile.preferred_payment, list):
                profile.preferred_payments = profile.preferred_payment
                profile.save()

def preferred_payment_to_array_reverse(apps, schema_editor):
    LicenseProfile = apps.get_model("brand", "LicenseProfile")
    for profile in LicenseProfile.objects.all():
        if profile.preferred_payments:
            profile.preferred_payment = profile.preferred_payments[0]
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0055_onboardingdatafetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='preferred_payments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.RunPython(preferred_payment_to_array, reverse_code=preferred_payment_to_array_reverse),
        migrations.RemoveField(
            model_name='licenseprofile',
            name='preferred_payment',
        ),
        migrations.RenameField(
            model_name='licenseprofile',
            old_name='preferred_payments',
            new_name='preferred_payment',
        ),

        migrations.AddField(
            model_name='licenseprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank City'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Routing Number'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Street'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Zip Code '),
        ),
        migrations.DeleteModel(
            name='BillingInformation',
        ),
    ]
