# Generated by Django 2.2 on 2021-01-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0056_auto_20210113_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Country'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='bank_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank State'),
        ),
    ]
