# Generated by Django 2.2 on 2021-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0057_auto_20210114_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingdatafetch',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('error', 'Error'), ('licence_data_not_found', 'Licence Data Not Found'), ('licence_association_not_found', 'Fetching'), ('owner_email_not_found', 'Owner Email Not Found'), ('owner_verification_sent', 'Owner Verification Sent'), ('verified', 'Verified'), ('inserting', 'Inserting'), ('complete', 'Complete')], default='not_started', max_length=255, verbose_name='Data From CRM Status'),
        ),
    ]
