# Generated by Django 2.2 on 2021-01-28 09:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0058_auto_20210118_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardingdatafetch',
            old_name='crm_data',
            new_name='crm_profile_data',
        ),
        migrations.RemoveField(
            model_name='onboardingdatafetch',
            name='status',
        ),
        migrations.AddField(
            model_name='onboardingdatafetch',
            name='crm_license_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='CRM License Data'),
        ),
        migrations.AddField(
            model_name='onboardingdatafetch',
            name='data_fetch_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('licence_association_not_found', 'Licence Association Not Found'), ('fetched', 'Fetched'), ('complete', 'Complete'), ('error', 'Error')], default='not_started', max_length=255, verbose_name='Data From CRM Status'),
        ),
        migrations.AddField(
            model_name='onboardingdatafetch',
            name='owner_verification_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('licence_data_not_found', 'Licence Data Not Found'), ('owner_email_not_found', 'Owner Email Not Found'), ('verification_code_sent', 'Verification Code Sent'), ('verified', 'Verified'), ('error', 'Error')], default='not_started', max_length=255, verbose_name='Owner Verification Status'),
        ),
    ]
