# Generated by Django 2.2 on 2021-02-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0060_auto_20210128_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Is Disabled'),
        ),
    ]
