# Generated by Django 2.2 on 2021-02-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0062_licenseprofile_have_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationoverview',
            name='autoflower',
            field=models.BooleanField(default=False, verbose_name='Autoflower'),
        ),
        migrations.AlterField(
            model_name='cultivationoverview',
            name='full_season',
            field=models.BooleanField(default=False, verbose_name='Full Season'),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='have_transportation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Have Transportation'),
        ),
    ]
