# Generated by Django 2.2 on 2021-02-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0063_auto_20210218_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='permission.Permission', verbose_name='Permissions'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
