# Generated by Django 2.2 on 2021-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0064_auto_20210219_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuserinvite',
            name='is_invite_accepted',
            field=models.BooleanField(default=False, verbose_name='Is Invite Accepted'),
        ),
        migrations.AlterField(
            model_name='organizationuserinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('user_joining_platform', 'User Joining Platform'), ('completed', 'Completed')], default='pending', max_length=60),
        ),
    ]
