# Generated by Django 2.2 on 2021-03-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0065_auto_20210225_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'organizational'}, to='permission.Permission', verbose_name='Permissions'),
        ),
    ]
