# Generated by Django 2.2 on 2021-03-01 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    License = apps.get_model("brand", "License")
    for license in License.objects.all():
        if not license.created_by:
            license.created_by = license.organization.created_by
            license.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0066_auto_20210301_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.RunPython(forward_func, reverse_code=reverse_func),
        migrations.AlterField(
            model_name='license',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
