# Generated by Django 2.2 on 2021-03-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0067_license_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='crm_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Owner EMAIL'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='crm_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Owner ID'),
        ),
    ]
