# Generated by Django 2.2 on 2021-03-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0068_auto_20210310_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request ID')),
                ('action_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Licenses', to='brand.License', verbose_name='License')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
