# Generated by Django 2.2 on 2021-04-15 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0069_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
