# Generated by Django 2.2 on 2021-05-12 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0071_nurseryoverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseryoverview',
            name='growing_medium',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
