# Generated by Django 2.2 on 2021-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivar', '0007_auto_20210309_0544'),
        ('brand', '0072_auto_20210512_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryoverview',
            name='pending_cultivars',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='pending_for_approval'), related_name='nursery_overview', to='cultivar.Cultivar', verbose_name='Pending cultivars'),
        ),
    ]
