# Generated by Django 2.2 on 2021-05-24 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0073_nurseryoverview_pending_cultivars'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryoverview',
            name='ipm_practices_qa',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='IPM Practices & QA'),
        ),
    ]
