# Generated by Django 2.2 on 2021-05-31 06:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0074_nurseryoverview_ipm_practices_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='crm_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='CRM Output'),
        ),
    ]
