# Generated by Django 2.2 on 2021-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0075_license_crm_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID - Brand'),
        ),
        migrations.AlterField(
            model_name='license',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID - License'),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID - Profile(Account/Vendor)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zoho_crm_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM ID - Organization'),
        ),
    ]
