# Generated by Django 2.2 on 2021-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0076_auto_20210614_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_notified_before_expiry',
            field=models.BooleanField(default=False, verbose_name='Is Notified Before Expiry'),
        ),
    ]
