# Generated by Django 2.2 on 2021-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0078_license_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_contract_downloaded',
            field=models.BooleanField(default=False, verbose_name='Is Contract Downloaded For Offline Sign'),
        ),
    ]
