# Generated by Django 2.2 on 2021-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0079_license_is_contract_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='zoho_crm_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM Account ID'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='zoho_crm_vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho CRM  Vendor ID'),
        ),
    ]
