# Generated by Django 2.2 on 2021-07-09 07:27

from django.db import migrations

def forward_func(apps, schema_editor):
    print()
    LicenseProfile = apps.get_model("brand", "LicenseProfile")
    for license_profile in LicenseProfile.objects.all().select_related('license'):
        if license_profile.license.is_buyer:
            license_profile.zoho_crm_account_id = license_profile.zoho_crm_id
        if license_profile.license.is_seller:
            license_profile.zoho_crm_vendor_id = license_profile.zoho_crm_id
            if license_profile.license.is_buyer:
                print(f"License: {license_profile.license.pk}, Profile: {license_profile.pk} is Buyer&Seller")
        license_profile.save()

def reverse_func(apps, schema_editor):
    LicenseProfile = apps.get_model("brand", "LicenseProfile")
    for license_profile in LicenseProfile.objects.all().select_related('license'):
        if license_profile.license.is_buyer:
            license_profile.zoho_crm_id = license_profile.zoho_crm_account_id
        elif license_profile.license.is_seller:
            license_profile.zoho_crm_id = license_profile.zoho_crm_vendor_id
        license_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0080_auto_20210709_0725'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
