# Generated by Django 2.2 on 2021-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0081_auto_20210709_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenseprofile',
            old_name='crm_owner_email',
            new_name='crm_account_owner_email',
        ),
        migrations.RenameField(
            model_name='licenseprofile',
            old_name='crm_owner_id',
            new_name='crm_account_owner_id',
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='crm_account_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Account Owner EMAIL'),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='crm_account_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Account Owner ID'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='crm_vendor_owner_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Vendor Owner EMAIL'),
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='crm_vendor_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CRM Vendor Owner ID'),
        ),
    ]
