# Generated by Django 2.2 on 2021-08-02 05:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0082_auto_20210714_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='resale_certificate_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resale Certificate Url'),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='cultivars_of_interest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='licenseprofile',
            name='product_of_interest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
