# Generated by Django 2.2 on 2021-08-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0083_auto_20210802_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='resale_certificate_url',
            new_name='uploaded_resale_certificate_to',
        ),
    ]
