# Generated by Django 2.2 on 2021-08-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0084_auto_20210802_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='uploaded_resale_certificate_to',
        ),
    ]
