# Generated by Django 2.2 on 2021-08-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0086_licenseprofile_signed_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Is Expired'),
        ),
    ]
