# Generated by Django 2.2 on 2021-08-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0087_license_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='is_expired',
        ),
    ]
