# Generated by Django 2.2 on 2021-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0088_remove_license_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='zoho_books_id',
            new_name='zoho_books_customer_id',
        ),
        migrations.AlterField(
            model_name='license',
            name='zoho_books_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Books Customer ID'),
        ),
        migrations.AddField(
            model_name='license',
            name='zoho_books_vendor_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zoho Books Vendor ID'),
        ),
    ]
