# Generated by Django 2.2 on 2021-08-16 14:17

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0089_auto_20210816_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='zoho_books_customer_id',
            new_name='zoho_books_customer_id_old',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='zoho_books_vendor_id',
            new_name='zoho_books_vendor_id_old',
        ),
        migrations.AddField(
            model_name='license',
            name='zoho_books_customer_ids',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='license',
            name='zoho_books_vendor_ids',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
