# Generated by Django 2.2 on 2021-08-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0090_auto_20210816_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseprofile',
            name='zoho_crm_id',
        ),
    ]
