# Generated by Django 2.2 on 2021-08-27 08:12

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0094_auto_20210827_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='client_id',
            field=models.PositiveIntegerField(default=brand.models.get_client_id, help_text='Randomly genrated 6 digit number.', unique=True, validators=[brand.models.client_id_validator]),
        ),
    ]
