# Generated by Django 2.2 on 2021-08-31 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0095_auto_20210827_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='books_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Books Output'),
        ),
    ]
