# Generated by Django 2.2 on 2021-09-06 13:36

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0096_license_books_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='books_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Books Output'),
        ),
        migrations.AlterField(
            model_name='license',
            name='crm_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='CRM Output'),
        ),
    ]
