# Generated by Django 2.2 on 2021-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0097_auto_20210906_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='business_dba',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='business DBA'),
        ),
    ]
