# Generated by Django 2.2 on 2021-09-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0100_license_cultivation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenseprofile',
            old_name='is_updated_in_crm',
            new_name='is_account_updated_in_crm',
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='is_vendor_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is Vendor Updated In CRM'),
        ),
        migrations.AlterField(
            model_name='license',
            name='is_updated_in_crm',
            field=models.BooleanField(default=False, verbose_name='Is License Updated In CRM'),
        ),
    ]
