# Generated by Django 2.2 on 2021-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0102_auto_20210924_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='business_dba',
        ),
        migrations.AddField(
            model_name='licenseprofile',
            name='business_dba',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='business DBA'),
        ),
    ]
