# Generated by Django 2.2 on 2021-09-30 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0103_auto_20211004_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseUserInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('is_invite_accepted', models.BooleanField(default=False, verbose_name='Is Invite Accepted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('user_joining_platform', 'User Joining Platform'), ('completed', 'Completed')], default='pending', max_length=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invites', to='brand.License', verbose_name='Licenses')),
                ('roles', models.ManyToManyField(related_name='user_invites', to='brand.OrganizationRole', verbose_name='Roles')),
            ],
            options={
                'verbose_name': 'License User Invite',
                'verbose_name_plural': 'License User Invites',
            },
        ),
    ]
