# Generated by Django 2.2 on 2021-11-26 06:01

from django.db import migrations

def forward_func(apps, schema_editor):
    License = apps.get_model("brand", "License")
    print()
    for obj in License.objects.filter(status='expired'):
        obj.status = obj.status_before_expiry or 'completed'
        obj.license_status = 'Expired'
        obj.save()
        print(f"{obj.id} : {obj.status} : {obj.status_before_expiry}")

def reverse_func(apps, schema_editor):
    License = apps.get_model("brand", "License")
    for obj in License.objects.filter(license_status='Expired'):
        obj.status_before_expiry = obj.status
        obj.status = 'expired'
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0105_auto_20210930_1143'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
