# Generated by Django 2.2 on 2021-11-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0106_auto_20211126_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=100, null=True, verbose_name='License Status'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='not_started', max_length=20, verbose_name='Status'),
        ),
    ]
