# Generated by Django 2.2 on 2021-12-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0109_licenseprofile_is_confia_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileReport',
        ),
    ]
