# Generated by Django 2.2 on 2021-12-10 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0111_profilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='selected_profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None, verbose_name='Selected Profiles'),
        ),
    ]
