# Generated by Django 2.2 on 2022-01-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0114_auto_20220110_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecategory',
            name='programs',
        ),
    ]
