# Generated by Django 2.2 on 2022-03-22 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0116_licenseuserinvite_last_token_generated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='cart_notification_user',
            field=models.ManyToManyField(blank=True, related_name='cart_notification_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Cart Notification User'),
        ),
    ]
