# Generated by Django 2.2 on 2022-03-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0117_license_cart_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='cart_notification_user',
            new_name='cart_notification_users',
        ),
    ]
