# Generated by Django 2.2 on 2022-03-22 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0118_auto_20220322_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='cart_notification_users',
            field=models.ManyToManyField(blank=True, related_name='cart_notification_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Cart Notification Users'),
        ),
    ]
