from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import (ArrayField, JSONField,)

class LabTest(models.Model):
    """
    Lab test model.
    """
    labtest_crm_id = models.CharField(_('LabTest CRM ID'), blank=True, null=True, max_length=100)
    Abamectin = models.CharField(_('Abamectin'), blank=True, null=True, max_length=255)
    Acephate = models.CharField(_('Acephate'), blank=True, null=True, max_length=255)
    Acequinocyl = models.CharField(_('Acequinocyl'), blank=True, null=True, max_length=255)
    Acetamiprid = models.CharField(_('Acetamiprid'), blank=True, null=True, max_length=255)
    Aflatoxin_B1 = models.CharField(_('Aflatoxin_B1'), blank=True, null=True, max_length=255)
    Aflatoxin_B2 = models.CharField(_('Aflatoxin_B2'), blank=True, null=True, max_length=255)
    Aflatoxin_G1 = models.CharField(_('Aflatoxin_G1'), blank=True, null=True, max_length=255)
    Aflatoxin_G2 = models.CharField(_('Aflatoxin_G2'), blank=True, null=True, max_length=255)
    Aldicarb = models.CharField(_('Aldicarb'), blank=True, null=True, max_length=255)
    Arsenic = models.CharField(_('Arsenic'), blank=True, null=True, max_length=255)
    Aspergillus = models.CharField(_('Aspergillus'), blank=True, null=True, max_length=255)
    Aspergillus_flavus = models.CharField(_('Aspergillus_flavus'), blank=True, null=True, max_length=255)
    Aspergillus_fumigatus = models.CharField(_('Aspergillus_fumigatus'), blank=True, null=True, max_length=255)
    Aspergillus_nigers = models.CharField(_('Aspergillus_nigers'), blank=True, null=True, max_length=255)
    Aspergillus_terreus = models.CharField(_('Aspergillus_terreus'), blank=True, null=True, max_length=255)
    Azoxystrobin = models.CharField(_('Azoxystrobin'), blank=True, null=True, max_length=255)
    B_Caryophyllene_oxide = models.CharField(_('B_Caryophyllene_oxide'), blank=True, null=True, max_length=255)
    Benzene = models.CharField(_('Benzene'), blank=True, null=True, max_length=255)
    Bifenazate = models.CharField(_('Bifenazate'), blank=True, null=True, max_length=255)
    Bifenthrin = models.CharField(_('Bifenthrin'), blank=True, null=True, max_length=255)
    Borneol = models.CharField(_('Borneol'), blank=True, null=True, max_length=255)
    Boscalid = models.CharField(_('Boscalid'), blank=True, null=True, max_length=255)
    Box_Folder_Name = models.CharField(_('Box_Folder_Name'), blank=True, null=True, max_length=255)
    Box_Lab_Test_Folder_ID = models.CharField(_('Box_Lab_Test_Folder_ID'), blank=True, null=True, max_length=100)
    Box_Link = models.URLField(_('Box_Link'), blank=True, null=True, max_length=255)
    CBC = models.FloatField(_('CBC'), blank=True, null=True, max_length=255)
    CBCA = models.FloatField(_('CBCA'), blank=True, null=True, max_length=255)
    CBD = models.FloatField(_('CBD'), blank=True, null=True, max_length=255)
    CBDA = models.FloatField(_('CBDA'), blank=True, null=True, max_length=255)
    CBDV = models.FloatField(_('CBDV'), blank=True, null=True, max_length=255)
    CBDVA = models.FloatField(_('CBDVA'), blank=True, null=True, max_length=255)
    CBG = models.FloatField(_('CBG'), blank=True, null=True, max_length=255)
    CBGA = models.FloatField(_('CBGA'), blank=True, null=True, max_length=255)
    CBL = models.FloatField(_('CBL'), blank=True, null=True, max_length=255)
    CBN = models.FloatField(_('CBN'), blank=True, null=True, max_length=255)
    Cadmium = models.CharField(_('Cadmium'), blank=True, null=True, max_length=255)
    Camphene = models.CharField(_('Camphene'), blank=True, null=True, max_length=255)
    Camphor = models.CharField(_('Camphor'), blank=True, null=True, max_length=255)
    Cannabinoids = models.CharField(_('Cannabinoids'), blank=True, null=True, max_length=255)
    Captan = models.CharField(_('Captan'), blank=True, null=True, max_length=255)
    Carbaryl = models.CharField(_('Carbaryl'), blank=True, null=True, max_length=255)
    Carbofuran = models.CharField(_('Carbofuran'), blank=True, null=True, max_length=255)
    Chlordane = models.CharField(_('Chlordane'), blank=True, null=True, max_length=255)
    Chlorfenapyr = models.CharField(_('Chlorfenapyr'), blank=True, null=True, max_length=255)
    Chloroform = models.CharField(_('Chloroform'), blank=True, null=True, max_length=255)
    Chlorpyrifos = models.CharField(_('Chlorpyrifos'), blank=True, null=True, max_length=255)
    Chlortraniliprole = models.CharField(_('Chlortraniliprole'), blank=True, null=True, max_length=255)
    Client_Code = models.CharField(_('Client_Code'), blank=True, null=True, max_length=255)
    Clofentazine = models.CharField(_('Clofentazine'), blank=True, null=True, max_length=255)
    Coumaphos = models.CharField(_('Coumaphos'), blank=True, null=True, max_length=255)
    Created_Time = models.DateField(auto_now=False, blank=True, null=True)
    Cultivar = models.CharField(_('Cultivar'), blank=True, null=True, max_length=255)
    Cyfluthrin = models.CharField(_('Cyfluthrin'), blank=True, null=True, max_length=255)
    Cypermethrin = models.CharField(_('Cypermethrin'), blank=True, null=True, max_length=255)
    Daminozide = models.CharField(_('Daminozide'), blank=True, null=True, max_length=255)
    Date_Harvested = models.DateField(auto_now=False, blank=True, null=True)
    Date_Received = models.DateField(auto_now=False, blank=True, null=True)
    Date_Reported = models.DateField(auto_now=False, blank=True, null=True)
    Date_Tested = models.DateField(auto_now=False, blank=True, null=True)
    Diazinon = models.CharField(_('Diazinon'), blank=True, null=True, max_length=255)
    Dichloroethane = models.CharField(_('1,2-Dichloroethane'), blank=True, null=True, max_length=255)
    Dichlorvos = models.CharField(_('Dichlorvos'), blank=True, null=True, max_length=255)
    Dimethoate = models.CharField(_('Dimethoate'), blank=True, null=True, max_length=255)
    Dimethomorph = models.CharField(_('Dimethomorph'), blank=True, null=True, max_length=255)
    E_Coli = models.CharField(_('E_Coli'), blank=True, null=True, max_length=255)
    Eicosane = models.CharField(_('Eicosane'), blank=True, null=True, max_length=255)
    Ethoprop = models.CharField(_('Ethoprop'), blank=True, null=True, max_length=255)
    Ethylene_Oxide = models.CharField(_('Ethylene Oxide'), blank=True, null=True, max_length=255)
    Etofenprox = models.CharField(_('Etofenprox'), blank=True, null=True, max_length=255)
    Etoxazole = models.CharField(_('Etoxazole'), blank=True, null=True, max_length=255)
    Eucalyptol = models.CharField(_('Eucalyptol'), blank=True, null=True, max_length=255)
    Farnesene = models.CharField(_('Farnesene'), blank=True, null=True, max_length=255)
    Fenchol = models.CharField(_('Fenchol'), blank=True, null=True, max_length=255)
    Fenhexamid = models.CharField(_('Fenhexamid'), blank=True, null=True, max_length=255)
    Fenoxycarb = models.CharField(_('Fenoxycarb'), blank=True, null=True, max_length=255)
    Fenpyroximate = models.CharField(_('Fenpyroximate'), blank=True, null=True, max_length=255)
    Filth_Foreign_Matter = models.CharField(_('Filth & Foreign Matter PASS/FAIL'), blank=True, null=True, max_length=255)
    Fipronil = models.CharField(_('Fipronil'), blank=True, null=True, max_length=255)
    Flonicamid = models.CharField(_('Flonicamid'), blank=True, null=True, max_length=255)
    Fludoxinil = models.CharField(_('Fludoxinil'), blank=True, null=True, max_length=255)
    Geraniol = models.CharField(_('Geraniol'), blank=True, null=True, max_length=255)
    Guaiol = models.CharField(_('Guaiol'), blank=True, null=True, max_length=255)
    Heavy_Metals = models.CharField(_('Heavy Metals PASS/FAIL'), blank=True, null=True, max_length=255)
    Hexythiazox = models.CharField(_('Hexythiazox'), blank=True, null=True, max_length=255)
    Homogeneity = models.CharField(_('Homogeneity PASS/FAIL'), blank=True, null=True, max_length=255)
    Imazilil = models.CharField(_('Imazilil'), blank=True, null=True, max_length=255)
    Imidacloprid = models.CharField(_('Imidacloprid'), blank=True, null=True, max_length=255)
    Inventory_SKU = models.CharField(_('Inventory_SKU'), blank=True, null=True, max_length=255)
    Kresoxim_methyl = models.CharField(_('Kresoxim_methyl'), blank=True, null=True, max_length=255)
    L_fenchone = models.CharField(_('L_fenchone'), blank=True, null=True, max_length=255)
    Last_Activity_Time = models.DateTimeField(auto_now=False, blank=True, null=True)
    Lead = models.CharField(_('Lead'), blank=True, null=True, max_length=255)
    Linalool = models.CharField(_('Linalool'), blank=True, null=True, max_length=255)
    Malathion = models.CharField(_('Malathion'), blank=True, null=True, max_length=255)
    Menthol = models.CharField(_('Menthol'), blank=True, null=True, max_length=255)
    Mercury = models.CharField(_('Mercury'), blank=True, null=True, max_length=255)
    Metalaxyl = models.CharField(_('Metalaxyl'), blank=True, null=True, max_length=255)
    Methiocarb = models.CharField(_('Methiocarb'), blank=True, null=True, max_length=255)
    Methomyl = models.CharField(_('Methomyl'), blank=True, null=True, max_length=255)
    Methylene_chloride = models.CharField(_('Methylene chloride'), blank=True, null=True, max_length=255)
    Mevinphos = models.CharField(_('Mevinphos'), blank=True, null=True, max_length=255)
    Microbiological_Contamination = models.CharField(_('Microbiological Contamination PASS/FAIL'), blank=True, null=True, max_length=255)
    Modified_By = models.CharField(_('Modified_By'), blank=True, null=True, max_length=100)
    Modified_Time = models.DateField(auto_now=False, blank=True, null=True)
    Moisture = models.CharField(_('Moisture'), blank=True, null=True, max_length=255)
    MoistureL = models.CharField(_('Moisture PASS/FAIL'), blank=True, null=True, max_length=255)
    Myclobutanil = models.CharField(_('Myclobutanil'), blank=True, null=True, max_length=255)
    Mycotoxins_PASS_FAIL = models.CharField(_('Mycotoxins_PASS_FAIL'), blank=True, null=True, max_length=255)
    Myrcene = models.CharField(_('Myrcene'), blank=True, null=True, max_length=255)
    Naled = models.CharField(_('Naled'), blank=True, null=True, max_length=255)
    Name = models.CharField(_('Name'), blank=True, null=True, max_length=255)
    Ochratoxin = models.CharField(_('Ochratoxin'), blank=True, null=True, max_length=255)
    Ocimene = models.CharField(_('Ocimene'), blank=True, null=True, max_length=255)
    Oxamyl = models.CharField(_('Oxamyl'), blank=True, null=True, max_length=255)
    Paclobutrazole = models.CharField(_('Paclobutrazole'), blank=True, null=True, max_length=255)
    Parathion_methyl = models.CharField(_('Parathion_methyl'), blank=True, null=True, max_length=255)
    Pentachloronitrobenzene = models.CharField(_('Pentachloronitrobenzene'), blank=True, null=True, max_length=255)
    Permethrin = models.CharField(_('Permethrin'), blank=True, null=True, max_length=255)
    Pesticides = models.CharField(_('Pesticides PASS/FAIL'), blank=True, null=True, max_length=255)
    Phosmet = models.CharField(_('Phosmet'), blank=True, null=True, max_length=255)
    Piperonyl_butoxide = models.CharField(_('Piperonyl_butoxide'), blank=True, null=True, max_length=255)
    Prallethrin = models.CharField(_('Prallethrin'), blank=True, null=True, max_length=255)
    Propiconazole = models.CharField(_('Propiconazole'), blank=True, null=True, max_length=255)
    Propoxur = models.CharField(_('Propoxur'), blank=True, null=True, max_length=255)
    Pulegone = models.CharField(_('(+)-Pulegone'), blank=True, null=True, max_length=255)
    Pyrethrins = models.CharField(_('Pyrethrins'), blank=True, null=True, max_length=255)
    Pyridaben = models.CharField(_('Pyridaben'), blank=True, null=True, max_length=255)
    QC_Batch_es = models.CharField(_('QC_Batch_es'), blank=True, null=True, max_length=255)
    R_Limonene = models.CharField(_('R-Limonene'), blank=True, null=True, max_length=255)
    Record_Image = models.CharField(_('Record_Image'), blank=True, null=True, max_length=255)
    Relative_Standard_Deviation = models.CharField(_('Relative_Standard_Deviation'), blank=True, null=True, max_length=255)
    Sabinene = models.CharField(_('Sabinene'), blank=True, null=True, max_length=255)
    Salmonella = models.CharField(_('Salmonella'), blank=True, null=True, max_length=255)
    Sample_I_D = models.CharField(_('Sample_I_D'), blank=True, null=True, max_length=255)
    Sample_Type = models.CharField(_('Sample_Type'), blank=True, null=True, max_length=255)
    Service_Time = models.CharField(_('Service Time'), blank=True, null=True, max_length=255)
    Spinatoram = models.CharField(_('Spinatoram'), blank=True, null=True, max_length=255)
    Spinosad = models.CharField(_('Spinosad'), blank=True, null=True, max_length=255)
    Spiromesifen = models.CharField(_('Spiromesifen'), blank=True, null=True, max_length=255)
    Spirotetramat = models.CharField(_('Spirotetramat'), blank=True, null=True, max_length=255)
    Spiroxamine = models.CharField(_('Spiroxamine'), blank=True, null=True, max_length=255)
    THC = models.FloatField(_('THC'), blank=True, null=True, max_length=255)
    THCA = models.FloatField(_('THCA'), blank=True, null=True, max_length=255)
    THCV = models.FloatField(_('THCV'), blank=True, null=True, max_length=255)
    THCVA = models.FloatField(_('THCVA'), blank=True, null=True, max_length=255)
    Tag = models.CharField(_('Tag'), blank=True, null=True, max_length=255)
    Tebuconazole = models.CharField(_('Tebuconazole'), blank=True, null=True, max_length=255)
    Terpinolene = models.CharField(_('Terpinolene'), blank=True, null=True, max_length=255)
    Test_Upload = models.CharField(_('Test_Upload'), blank=True, null=True, max_length=255)
    Tests_Performed = ArrayField(models.CharField(max_length=50), blank=True, null=True)
    Thiacloprid = models.CharField(_('Thiacloprid'), blank=True, null=True, max_length=255)
    Thiamethoxam = models.CharField(_('Thiamethoxam'), blank=True, null=True, max_length=255)
    Total_Aflatoxin = models.CharField(_('Total_Aflatoxin'), blank=True, null=True, max_length=255)
    Total_CBD = models.FloatField(_('Total_CBD'), blank=True, null=True, max_length=255)
    Total_Cannabinoids = models.FloatField(_('Total_Cannabinoids'), blank=True, null=True, max_length=255)
    Total_Residual_Solvent = models.CharField(_('Total Residual Solvent PASS/FAIL'), blank=True, null=True, max_length=255)
    Total_THC = models.FloatField(_('Total_THC'), blank=True, null=True, max_length=255)
    Total_Terpenes = models.CharField(_('Total_Terpenes'), blank=True, null=True, max_length=255)
    Total_Xylenes = models.CharField(_('Total Xylenes'), blank=True, null=True, max_length=255)
    Trichloroethylene = models.CharField(_('Trichloroethylene'), blank=True, null=True, max_length=255)
    Trifloxystrobin = models.CharField(_('Trifloxystrobin'), blank=True, null=True, max_length=255)
    Valencene = models.CharField(_('Valencene'), blank=True, null=True, max_length=255)
    a_phellandrene = models.CharField(_('a_phellandrene'), blank=True, null=True, max_length=255)
    acetone = models.CharField(_('acetone'), blank=True, null=True, max_length=255)
    acetonitrile = models.CharField(_('acetonitrile'), blank=True, null=True, max_length=255)
    alpha_Bisabolol = models.CharField(_('alpha_Bisabolol'), blank=True, null=True, max_length=255)
    alpha_Humulene = models.CharField(_('alpha-Humulene'), blank=True, null=True, max_length=255)
    alpha_Terpineol = models.CharField(_('alpha-Terpineol'), blank=True, null=True, max_length=255)
    alpha_pinene = models.CharField(_('alpha-pinene'), blank=True, null=True, max_length=255)
    beta_Caryophyllene = models.CharField(_('beta-Caryophyllene'), blank=True, null=True, max_length=255)
    beta_Pinene = models.CharField(_('beta-Pinene'), blank=True, null=True, max_length=255)
    butanone = models.CharField(_('butanone'), blank=True, null=True, max_length=255)
    cis_Nerolidol = models.CharField(_('cis_Nerolidol'), blank=True, null=True, max_length=255)
    d_8_THC = models.FloatField(_('d_8_THC'), blank=True, null=True, max_length=255)
    ethanol = models.CharField(_('ethanol'), blank=True, null=True, max_length=255)
    ether = models.CharField(_('ether'), blank=True, null=True, max_length=255)
    ethyl_acetate = models.CharField(_('ethyl acetate'), blank=True, null=True, max_length=255)
    four_methyl_two_pentanone = models.CharField(_('4-methyl-2-pentanone'), blank=True, null=True, max_length=255)
    gamma_Terpinene = models.CharField(_('gamma-Terpinene'), blank=True, null=True, max_length=255)
    methanol = models.CharField(_('methanol'), blank=True, null=True, max_length=255)
    n_Heptane = models.CharField(_('n-Heptane'), blank=True, null=True, max_length=255)
    n_butane = models.CharField(_('n-butane'), blank=True, null=True, max_length=255)
    n_hexane = models.CharField(_('n-hexane'), blank=True, null=True, max_length=255)
    n_pentane = models.CharField(_('n-pentane'), blank=True, null=True, max_length=255)
    one_butanol = models.CharField(_('1-butanol'), blank=True, null=True, max_length=255)
    one_butanol = models.CharField(_('2-butanol'), blank=True, null=True, max_length=255)
    one_pentanol = models.CharField(_('1-pentanol'), blank=True, null=True, max_length=255)
    one_propanol = models.CharField(_('1-propanol'), blank=True, null=True, max_length=255)
    phytol = models.CharField(_('phytol'), blank=True, null=True, max_length=255)
    propane = models.CharField(_('propane'), blank=True, null=True, max_length=255)
    tert_butyl_methyl_ether = models.CharField(_('tert-butyl methyl ether (MTBE)'), blank=True, null=True, max_length=255)
    three_Carene = models.CharField(_('3-Carene'), blank=True, null=True, max_length=255)
    three_methyl_one_butanol = models.CharField(_('3-methyl-1-butanol'), blank=True, null=True, max_length=255)
    toluene = models.CharField(_('toluene'), blank=True, null=True, max_length=255)
    trans_Nerolidol = models.CharField(_('trans_Nerolidol'), blank=True, null=True, max_length=255)
    two_methyl_butane = models.CharField(_('2-methyl butane'), blank=True, null=True, max_length=255)
    two_methyl_one_propanol = models.CharField(_('2-methyl-1-propanol'), blank=True, null=True, max_length=255)
    two_methyl_propane = models.CharField(_('2-methyl propane'), blank=True, null=True, max_length=255)
    two_propanol = models.CharField(_('2-propanol'), blank=True, null=True, max_length=255)
    two_butanol = models.CharField(_('2-butanol'), blank=True, null=True, max_length=255)
    Associated_Vendor = models.CharField(_('Associated_Vendor'), blank=True, null=True, max_length=255)
    
    def __str__(self):
        return self.Name