# Generated by Django 2.2 on 2021-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=255, verbose_name='Tier')),
                ('mcsp_fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='MCSP Fee(%)')),
                ('net_7_14', models.CharField(blank=True, max_length=255, null=True, verbose_name='Net 7-14(%)')),
                ('net_14_30', models.CharField(blank=True, max_length=255, null=True, verbose_name='Net 14-30(%)')),
                ('cash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cash(%)')),
                ('transportation_fee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transportation Fee/Mile($)')),
            ],
            options={
                'verbose_name': 'Order Variable',
                'verbose_name_plural': 'Order Variables',
            },
        ),
    ]
