# Generated by Django 2.2 on 2021-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0002_custominventoryvariable_taxvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxvariable',
            name='cultivar_tax_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cultivar Tax Item'),
        ),
        migrations.AddField(
            model_name='taxvariable',
            name='trim_tax_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trim Tax Item'),
        ),
    ]
