# Generated by Django 2.2 on 2021-03-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0003_auto_20210308_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custominventoryvariable',
            options={'verbose_name': 'Vendor Inventory Variable', 'verbose_name_plural': 'Vendor Inventory Variables'},
        ),
    ]
