# Generated by Django 2.2 on 2021-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0004_auto_20210310_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='tier',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('no_tier', 'No Tier')], max_length=255, verbose_name='Tier'),
        ),
    ]
