# Generated by Django 2.2 on 2021-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0005_auto_20210318_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('from_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='From Email')),
                ('mailing_list_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mailing List ID')),
            ],
            options={
                'verbose_name': 'Campaign Variable',
                'verbose_name_plural': 'Campaign Variables',
            },
        ),
    ]
