# Generated by Django 2.2 on 2021-03-30 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0006_campaignvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignvariable',
            name='mailing_list_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
