# Generated by Django 2.2 on 2021-07-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0010_auto_20210728_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominventoryvariable',
            name='mcsp_fee_clones',
        ),
        migrations.RemoveField(
            model_name='custominventoryvariable',
            name='mcsp_fee_concentrates_isolates_terpenes',
        ),
        migrations.RemoveField(
            model_name='custominventoryvariable',
            name='mcsp_fee_flowers_trims',
        ),
    ]
