# Generated by Django 2.2 on 2021-07-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0011_auto_20210730_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominventoryvariable',
            old_name='mcsp_fee_per_pcs',
            new_name='mcsp_fee_clones',
        ),
        migrations.RenameField(
            model_name='custominventoryvariable',
            old_name='mcsp_fee_per_g',
            new_name='mcsp_fee_concentrates_isolates_terpenes',
        ),
        migrations.RenameField(
            model_name='custominventoryvariable',
            old_name='mcsp_fee',
            new_name='mcsp_fee_flowers_trims',
        ),
    ]
