# Generated by Django 2.2 on 2021-08-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0013_auto_20210730_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominventoryvariable',
            old_name='mcsp_fee_concentrates_isolates_terpenes',
            new_name='mcsp_fee_concentrates',
        ),
        migrations.RenameField(
            model_name='custominventoryvariable',
            old_name='mcsp_fee_flowers_trims',
            new_name='mcsp_fee_flowers',
        ),
    ]
