# Generated by Django 2.2 on 2021-08-10 09:47

from django.db import migrations, models
from django.db.models import (F,)

def forward_func(apps, schema_editor):
    CustomInventoryVariable = apps.get_model("fee_variable", "CustomInventoryVariable")
    CustomInventoryVariable.objects.all().update(mcsp_fee_trims=F('mcsp_fee_flowers'))

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0014_auto_20210810_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominventoryvariable',
            name='mcsp_fee_isolates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This percentage will be used in MCSP Fee calculation for Isolates.', max_digits=6, null=True, verbose_name='MCSP Fee - Isolates (%)'),
        ),
        migrations.AddField(
            model_name='custominventoryvariable',
            name='mcsp_fee_terpenes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This percentage will be used in MCSP Fee calculation for Terpenes.', max_digits=6, null=True, verbose_name='MCSP Fee - Terpenes (%)'),
        ),
        migrations.AddField(
            model_name='custominventoryvariable',
            name='mcsp_fee_trims',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This fee will be for Trims.', max_digits=6, null=True, verbose_name='MCSP Fee - Trims ($/lb)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_concentrates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This percentage will be used in MCSP Fee calculation for Concentrates.', max_digits=6, null=True, verbose_name='MCSP Fee - Concentrates (%)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_flowers',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This fee will be for Flowers.', max_digits=6, null=True, verbose_name='MCSP Fee - Flowers ($/lb)'),
        ),
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
