# Generated by Django 2.2 on 2021-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0015_auto_20210810_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_clones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Clones ($/pcs)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_concentrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Concentrates (%)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_flowers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Flowers ($/lb)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_isolates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Isolates (%)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_terpenes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Terpenes (%)'),
        ),
        migrations.AlterField(
            model_name='custominventoryvariable',
            name='mcsp_fee_trims',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='MCSP Fee - Trims ($/lb)'),
        ),
    ]
