# Generated by Django 2.2 on 2021-10-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0017_auto_20210824_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinventorydefaultaccounts',
            name='inventory_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default inventory Account'),
        ),
        migrations.AlterField(
            model_name='vendorinventorydefaultaccounts',
            name='purchase_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Purchase Account'),
        ),
        migrations.AlterField(
            model_name='vendorinventorydefaultaccounts',
            name='sales_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default Sales Account'),
        ),
        migrations.CreateModel(
            name='VendorInventoryCategoryAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item_category', models.CharField(choices=[('Flower - Tops', 'Flower - Tops'), ('Flower - Small', 'Flower - Small'), ('Trim', 'Trim'), ('Isolates - CBD', 'Isolates - CBD'), ('Isolates - THC', 'Isolates - THC'), ('Isolates - CBG', 'Isolates - CBG'), ('Isolates - CBN', 'Isolates - CBN'), ('Crude Oil - THC', 'Crude Oil - THC'), ('Crude Oil - CBD', 'Crude Oil - CBD'), ('Distillate Oil - THC', 'Distillate Oil - THC'), ('Distillate Oil - CBD', 'Distillate Oil - CBD'), ('Shatter', 'Shatter'), ('Sauce', 'Sauce'), ('Crumble', 'Crumble'), ('Kief', 'Kief'), ('Terpenes - Cultivar Specific', 'Terpenes - Cultivar Specific'), ('Terpenes - Cultivar Blended', 'Terpenes - Cultivar Blended'), ('Clones', 'Clones')], max_length=50, verbose_name='Item Category')),
                ('sales_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sales Account')),
                ('purchase_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purchase Account')),
                ('inventory_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='inventory Account')),
                ('default_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_accounts_set', to='fee_variable.VendorInventoryDefaultAccounts', verbose_name='Default Accounts')),
            ],
            options={
                'verbose_name': 'Vendor Inventory Category Accounts',
                'verbose_name_plural': 'Vendor Inventory Category Accounts',
            },
        ),
    ]
