# Generated by Django 2.2 on 2021-10-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0018_auto_20211014_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorinventorycategoryaccounts',
            unique_together={('default_accounts', 'item_category')},
        ),
    ]
