# Generated by Django 2.2 on 2021-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0019_auto_20211018_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxvariable',
            old_name='cultivar_tax',
            new_name='dried_flower_tax',
        ),
        migrations.RenameField(
            model_name='taxvariable',
            old_name='cultivar_tax_item',
            new_name='dried_flower_tax_item',
        ),
        migrations.RenameField(
            model_name='taxvariable',
            old_name='trim_tax',
            new_name='dried_leaf_tax',
        ),
        migrations.RenameField(
            model_name='taxvariable',
            old_name='trim_tax_item',
            new_name='dried_leaf_tax_item',
        ),
        migrations.AddField(
            model_name='taxvariable',
            name='fresh_plant_tax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fresh Plant Tax'),
        ),
        migrations.AddField(
            model_name='taxvariable',
            name='fresh_plant_tax_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fresh Plant Tax Item'),
        ),
    ]
