# Generated by Django 2.2 on 2021-11-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0021_auto_20211110_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('qr_code_size', models.IntegerField(blank=True, help_text='The width and height of the QR code displayed on your image.This is the minimum pixel size of your QR code image.Actual size of the QR code can be slightly bigger depending on data and configuration.', null=True, verbose_name='QR Code Size')),
            ],
            options={
                'verbose_name': 'QR Code Variable',
                'verbose_name_plural': 'QR Code Variables',
            },
        ),
    ]
