# Generated by Django 2.2 on 2022-01-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0115_remove_profilecategory_programs'),
        ('fee_variable', '0023_agreement_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='agreement',
        ),
        migrations.CreateModel(
            name='ProgramProfileCategoryAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_profile_category_agreement_set', to='fee_variable.Agreement', verbose_name='Agreement')),
                ('profile_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_profile_category_agreement_set', to='brand.ProfileCategory', verbose_name='Profile Category')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_profile_category_agreement_set', to='fee_variable.Program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Profile Category Agreement',
                'verbose_name_plural': 'Program Profile Category Agreement',
                'unique_together': {('program', 'profile_category')},
            },
        ),
    ]
