# Generated by Django 2.2 on 2022-03-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0025_auto_20220225_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('order_page_sales_agreement', 'Order Page Sales Agreement')], max_length=255, unique=True, verbose_name='Label')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'File Link',
                'verbose_name_plural': 'File Links',
            },
        ),
    ]
