# Generated by Django 2.2 on 2022-03-17 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0026_filelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelink',
            name='box_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('\\d{3,}')], verbose_name='BOX File ID'),
        ),
    ]
