# Generated by Django 2.2 on 2022-03-17 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_variable', '0027_filelink_box_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='box_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('\\d{3,}', 'Enter a valid Box file ID')], verbose_name='BOX File ID'),
        ),
        migrations.AlterField(
            model_name='filelink',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
