# Generated by Django 2.2 on 2020-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='Associated_Vendor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Associated_Vendor'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='two_butanol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2-butanol'),
        ),
    ]
