# Generated by Django 2.2 on 2020-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0002_auto_20200703_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='Service_Time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Time'),
        ),
    ]
