# Generated by Django 2.2 on 2020-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0003_auto_20200703_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='CBC',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBC'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBCA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBCA'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBD',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBD'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBDA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBDA'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBDV',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBDV'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBDVA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBDVA'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBG',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBG'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBGA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBGA'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBL',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBL'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='CBN',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='CBN'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='THC',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='THC'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='THCA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='THCA'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='THCV',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='THCV'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='THCVA',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='THCVA'),
        ),
    ]
