# Generated by Django 2.2 on 2020-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0004_auto_20200923_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='Total_CBD',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total_CBD'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='Total_Cannabinoids',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total_Cannabinoids'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='Total_THC',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total_THC'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='d_8_THC',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='d_8_THC'),
        ),
    ]
