# Generated by Django 2.2 on 2021-07-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0005_auto_20200924_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='Total_Terpenes',
            new_name='Total_Terpenes_Old',
        ),
    ]
