# Generated by Django 2.2 on 2021-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0006_auto_20210722_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='Total_Terpenes',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Total_Terpenes'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='Total_Terpenes_Old',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total_Terpenes_Old'),
        ),
    ]
