# Generated by Django 2.2 on 2021-11-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0008_auto_20210722_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='Modified_By',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modified_By'),
        ),
    ]
