# Generated by Django 2.2 on 2021-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_ordervariable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordervariable',
            options={'verbose_name': 'Fees & Variables'},
        ),
        migrations.AddField(
            model_name='ordervariable',
            name='tier',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=255, verbose_name='Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordervariable',
            name='program_type',
            field=models.CharField(choices=[('ifp', 'IFP Program'), ('seller', 'Seller Program')], max_length=255, verbose_name='Program'),
        ),
    ]
