# Generated by Django 2.2 on 2021-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20210223_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordervariable',
            options={'verbose_name': 'Fees & Variables', 'verbose_name_plural': 'Fees & Variables'},
        ),
        migrations.AlterField(
            model_name='ordervariable',
            name='program_type',
            field=models.CharField(choices=[('ifp', 'IFP Program'), ('seller', 'Seller Program')], max_length=255, verbose_name='Program Type'),
        ),
        migrations.AlterField(
            model_name='ordervariable',
            name='tier',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], max_length=255, verbose_name='Tier'),
        ),
    ]
