# Generated by Django 2.2 on 2021-03-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_auto_20210223_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderVariable',
        ),
    ]
