# Generated by Django 2.2 on 2021-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_delete_ordervariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiaCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_company_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='partnerCompanyId')),
                ('confia_member_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='confiaMemberId')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Confia Onboarding',
            },
        ),
    ]
