# Generated by Django 2.2 on 2022-01-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_auto_20220105_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxEventTracker',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Request ID')),
                ('stream_position', models.BigIntegerField(default=0, verbose_name='Request ID')),
                ('is_state_ideal', models.BooleanField(default=True, verbose_name='Is State Ideal')),
            ],
            options={
                'verbose_name': 'Box Event Tracker',
                'verbose_name_plural': 'Box Event Trackers',
            },
        ),
    ]
