# Generated by Django 2.2 on 2022-01-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0011_boxeventtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsign',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Program Name'),
        ),
        migrations.AddField(
            model_name='boxsign',
            name='signer_embed_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Signer Embed URL'),
        ),
        migrations.AlterField(
            model_name='boxeventtracker',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Tracker ID'),
        ),
        migrations.AlterField(
            model_name='boxeventtracker',
            name='stream_position',
            field=models.BigIntegerField(default=0, verbose_name='Stream Position'),
        ),
        migrations.AlterField(
            model_name='boxsign',
            name='output_file_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Action ID'),
        ),
        migrations.AlterUniqueTogether(
            name='boxsign',
            unique_together=set(),
        ),
    ]
