#key- field from CRM, value- field from user model.
CRM_FORMAT  = {
    "Contacts": {
        "id": "id",
        "Email": "email",
        "First_Name": "first_name",
        "Last_Name": "last_name",
        "Full_Name": "full_name",
        "Other_Country": "Other_Country",
        "Other_State": "Other_State",
        "Date_Of_Birth": "date_of_birth",
        "Other_City": "Other_City",
        "Other_Zip": "Other_Zip",
        "Phone": "phone",
        "Salutation":"Salutation",
        "Products_of_Interest":"Products_of_Interest",
        "Verified":"Verified",
        "Company_Contact":"Company_Contact",
        "Title":"Title",
        "Owner":"Owner",
        "Mobile":"Mobile",
        "Department":"Department",
        "Contact_Type":"Contact_Type",
        "Modified_By":"Modified_By",
        "Created_By":"Created_By",
        "Lead_Source":"Lead_Source",
        "Email_Opt_Out":"Email_Opt_Out",
        "Tag":"Tag",
        "Entity_Name_for_Accounting":"Entity_Name_for_Accounting",
        "box__Box_Folder_ID":"box__Box_Folder_ID",
        "Associated_Account":"Associated_Account",
        "Email_Personal":"Email_Personal",
        "Vendor_Name":"Vendor_Name",
        "Created_Time":"Created_Time",
        "Secondary_Email":"Secondary_Email",
        "Contact_Company_Role":"Contact_Company_Role",
        "Modified_Time":"Modified_Time",
        "Other_Phone":"Other_Phone",
        "Reporting_To":"Reporting_To",
        "Last_Activity_Time":"Last_Activity_Time",
        "Assistant_Name":"Assistant_Name",
        "Fax":"Fax",
        "Is_Record_Duplicate":"Is_Record_Duplicate",
        "Unsubscribed_Mode":"Unsubscribed_Mode",
        "Unsubscribed_Time":"Unsubscribed_Time",
        "Currency":"Currency",
        "Mailing_Street":"Mailing_Street",
        "Mailing_City":"city",
        "Mailing_State":"state",
        "Mailing_Zip":"zip_code",
        "Mailing_Country":"country",
        "Record_Image":"Record_Image",
        "First_Visited_Time":"First_Visited_Time",
        "Visitor_Score":"Visitor_Score",
        "Referrer":"Referrer",
        "Average_Time_Spent_Minutes":"Average_Time_Spent_Minutes",
        "Last_Visited_Time":"Last_Visited_Time",
        "First_Visited_URL":"First_Visited_URL",
        "Number_Of_Chats":"Number_Of_Chats",
        "Days_Visited":"Days_Visited",
        "Linkedin":"Linkedin",
        "Instagram":"Instagram",
        "Facebook":"Facebook",
        "Twitter":"Twitter",
        "Skype_ID":"Skype_ID",
    },
    "Vendors_X_Contacts": {
        "Currency": "Currency",
        "Exchange_Rate": "Exchange_Rate",
        "Record_Image": "Record_Image",
        "Name": "Name",
        "Contact_Company_Role": "Contact_Company_Role",
        "Contact": "Contact",
        "Vendor": "Vendor",
    },
    "Accounts_X_Contacts": {
        "Currency": "Currency",
        "Exchange_Rate": "Exchange_Rate",
        "Record_Image": "Record_Image",
        "Name": "Name",
        "Contact_Company_Role": "Contact_Company_Role",
        "Contacts": "Contacts",
        "Accounts": "Accounts",
    },
    "Brands": {
        "Brand_Category": "brand_category",
        "Name": "brand_name",
        "Owner": "brand_owner",
        "County": "brand_county",
        "Region": "region",
        "Email": "email",
        "Exchange_Rate": "Exchange_Rate",
        "Phone": "Phone",
        "Product_Categories": "profile_category",
        "State": "state",
        "Website": "website",
        "Ethics_Certifications": "Ethics_Certifications",
        "Appellations": "Appellation",
        "About_Brand": "about_brand",
        "interested_in_co_branding": "interested_in_co_branding",
        "have_marketing": "have_marketing",
        "featured_on_our_site": "featured_on_our_site_parse",
    },
    "Vendors": {
        "db_id": "db_id",
        "id": "id",
        "Layout": "layout_parse",
        #Farm Profile
        "Vendor_Name": "name",
        "Legal_Entity_Names": "Legal_Entity_Names",
        "Client_Code": "Client_Code",
        "Cultivation_Type": "cultivation_type_parse",
        "Vendor_Type": "vendor_type_parse",
        "County": "county",
        "Region": "region",
        "Special_Certifications": "ethics_and_certification_parse",
        "Appellations": "appellation",
        "Transportation_Method": "transportation_parse",
        "Program_Selection": "program_details_parse",
        "About_Company": "about",
        "Have_you_ever_had_issues_with_failed_Lab_tests": "issues_with_failed_labtest",
        # "Preferred_Payment_Method": "preferred_payment",
        #Farm contact
        "Farm_Contact_Name": "Farm_Contact_Name",
        "Last_Name": "Last_Name",
        "Title": "Title",
        "Phone": "company_phone",
        "Email": "company_email",
        "Contact_1": "employees_parse",
        "Contact_3": "employees_parse",
        "Contact_2": "employees_parse",
        "Owner1": "employees_parse",
        "Number_of_Employees": "no_of_employees",
        "Gate_Code": "Gate_Code",
        #Logistic - Vendor arragned
        "Vehicle_Make_Model": "Vehicle_Make_Model",
        "Drivers_License_Number": "Drivers_License_Number",
        "Driver_s_Name": "Driver_s_Name",
        "License_Plate_Number": "License_Plate_Number",
        #Compliance
        "Licenses_List": "licenses",
        "Sellers_Permit": "Sellers_Permit",
        "W9_Box_Link": "W9_Box_Link",
        "Sellers_Permit_Box_Link": "Sellers_Permit_Box_Link",
        "Sellers_Permit_Expiration_Date": "Sellers_Permit_Expiration_Date",
        #Cultivar Questionaire
        "Cultivars_List": "cultivars_parse",
        "Indoor_Mixed_Lighting_Type": "lighting_type",
        "Types_of_Nutrients_Used": "type_of_nutrients_parse",
        "Would_you_grow_genetics_suggested_by_Thrive": "interested_in_growing_genetics",
        "Which_third_party_lab_do_you_use": "which_third_party_lab_do_you_use",
        "Issues_with_Failed_Lab_Tests": "lab_test_issues",
        "Cultivation_Style_Indoor": "Cultivation_Style_Indoor",
        "Cultivation_Style_Outdoor": "Cultivation_Style_Outdoor",
        "Cultivation_Style_Dep_Greenhouse": "Cultivation_Style_Dep_Greenhouse",
        "Cultivation_Style_Autoflower": "Cultivation_Style_Autoflower",
        #Financial
        "Annual_Revenue": "Annual_Revenue",
        "Know_your_Annual_Budget": "know_annual_budget",
        "Yearly_Budget": "annual_budget",
        "Yearly_Revenue": "Yearly_Revenue",
        #Farm Questionaire
        "Do_you_work_with_other_Distributors": "other_distributors",
        "Can_you_Process_on_Site": "cr.process_on_site_parse",
        "Packaged_Flower_Line": "Packaged_Flower_Line",
        "Farm_Co_Branding_Interest": "Farm_Co_Branding_Interest",
        "Marketing_material": "Marketing_material",
        "Featured_on_our_website_and_social_media": "Featured_on_our_website_and_social_media",
        #Mailing/Billing address
        "Billing_Street": "billing_address.street_parse",
        "Billing_City": "billing_address.city_parse",
        "Billing_Zip_Code": "billing_address.zip_code_parse",
        "Billing_State": "billing_address.state_parse",
        "Billing_Country": "billing_address.country_parse",
        "Do_you_have_a_bank_account": "Do_you_have_a_bank_account",
        "Bank_Name": "Bank_Name",
        "Bank_Account_Number": "Bank_Account_Number",
        "Bank_Routing_Number": "Bank_Routing_Number",
        #Shipping address
        "Mailing_Street_Line_2": "mailing_address.street_line_2_parse",
        "Shipping_Street": "mailing_address.street_parse",
        "Shipping_City": "mailing_address.city_parse",
        "Shipping_Zip_Code": "mailing_address.zip_code_parse",
        "Shipping_State": "mailing_address.state_parse",
        "Shipping_Country": "mailing_address.country_parse",
        #Reference and Social Media
        "Reference_Links": "Reference_Links",
        "Reference_Link": "Reference_Link",
        "Twitter": "twitter",
        "Facebook": "facebook",
        "LinkedIn": "linkedIn",
        # "Instagram": "instagram",
        "Website": "website",
        #Other
        "IFP_Services_Provided": "IFP_Services_Provided",
        "Owner": "Owner",
        "Year_Founded": "Year_Founded",
        "Round_Trip_Mileage_from_Todd_Rd": "Round_Trip_Mileage_from_Todd_Rd",
        "GL_Account": "GL_Account",
        "IFP_Status": "IFP_Status",
        "Scale": "Scale",
        "Dama_Approved": "Dama_Approved",
        "Hide_Internal_Info": "Hide_Internal_Info",
        "Vendor_Type1": "Vendor_Type1",
        "Created_Time": "Created_Time",
        "Modified_Time": "Modified_Time",
        "Billing_Notes": "Billing_Notes",
        "Description": "Description",
        "Box_Folder_ID": "Box_Folder_ID",
        "Tag": "Tag",
        "Currency": "Currency",
        "Record_Image": "Record_Image",
        "Modified_By": "Modified_By",
        "Account_Number": "Account_Number",
        "Annual_Harvests": "Annual_Harvests",
        "Contract_Box_Link": "Contract_Box_Link",
        "Created_By": "Created_By",
        "Vendor_Product_s_Categories": "Vendor_Product_s_Categories",
        "Irrigation_and_Plumbing": "Irrigation_and_Plumbing",
        "Lighting": "Lighting",
        "Trim_Equipment": "Trim_Equipment",
        "Chemicals_and_Reagents": "Chemicals_and_Reagents",
        "Greenhouses": "Greenhouses",
        "Nutrients_Amendments": "Nutrients_Amendments",
        "Vendor_Product_Categories": "Vendor_Product_Categories",
        "Motors_and_Pumps": "Motors_and_Pumps",
        "Lab_Equipment": "Lab_Equipment",
        "Chilling_Equipment": "Chilling_Equipment",
        "Product_Storage": "Product_Storage",
        "Drying": "Drying",
        "Pesticides_Herbicides_and_Fungicides": "Pesticides_Herbicides_and_Fungicides",
        "Janitorial_Sanitation": "Janitorial_Sanitation",
        "Sprayers_Applicators": "Sprayers_Applicators",
        "Vendor_Service_s_Categories": "Vendor_Service_s_Categories",
        "Services_Provided": "Services_Provided",
    },
    "Licenses":{
        "id": "license_id",
        "Name": "license_number",
        "Legal_Business_Name": "legal_business_name",
        "License_Type": "license_type",
        "Expiration_Date": "expiration_date",
        "Business_DBA": "",
        "Issue_Date": "issue_date",
        "License_Box_Link": "uploaded_license_to",
        "Owner": "Owner",
        "Sellers_Permit_Box_Link": "uploaded_sellers_permit_to",
        "W9_Box_Link": "uploaded_w9_to",
        "Cultivation_Type": "cultivation_type",
        "License_Status": "license_status",
        "Account_Name_Lookup": "account_name_lookup",
        "Vendor_Name_Lookup": "vendor_name_lookup",
        "Verified": "verified",
        "Verified_by": "verified_by",
        "Verified_Date": "verified_date",
        #Premises Information
        "Premises_Address": "premises_address",
        "Premises_City": "premises_city",
        "Premises_Zipcode": "zip_code",
        "Premises_State": "premises_state",
        "Premises_County": "premises_county",
        "Premises_APN_Number": "premises_apn",
        #License Contact
        "Owner_First_Name": "owner_first_name",
        "Owner_Last_Name": "owner_last_name",
        "License_Email": "license_email",
        "License_Phone": "license_phone",
        "Title": "title",
        #Cultivation Overview
        # "Types_of_Nutrients": "co.type_of_nutrients",
        "Canopy_Square_Feet_Mixed_Light": "co.0.canopy_sqf_parse",
        "Annual_Harvests_Mixed_Light": "co.0.no_of_harvest_parse",
        "Plants_per_Cycle_Mixed_Light": "co.0.plants_per_cycle_parse",
        "Canopy_Square_Feet_Autoflower": "co.1.canopy_sqf_parse",
        "Annual_Harvests_Autoflower": "co.1.no_of_harvest_parse",
        "Plants_per_Cycle_Autoflower": "co.1.plants_per_cycle_parse",
        #Farm Profile
        "Ethics_Certification": "ethics_certification",
        "Region": "region",
        "Appellations": "appellation",
        "About_Farm": "about_farm",
        "Do_you_work_with_other_distributors": "do_you_work_with_other_distributors",
        "Have_you_had_an_issue_with_failed_lab_tests": "issues_with_failed_labtest_parse",
        "Lab_Test_Issues_Description": "lab_test_issues_description",
        #Crop Overview
        "Outdoor_Type": "outdoor_type",
        "Lighting_Type": "co.0.lighting_type",
        "Can_you_Process_Onsite": "cr.process_on_site_parse",
        "Yield_per_Square_Foot_Average_Mixed_Light": "cr.0.avg_yield_pr_sq_ft_parse",
        "Yield_per_Plant_Mixed_Light": "cr.0.yield_per_plant_parse",
        "Yield_Annual_Flower_Tops_Mixed_Light": "cr.0.yield_annual_flower_tops_parse",
        "Yield_Annual_Flower_Smalls_Mixed_Light": "cr.0.yield_annual_flower_smalls_parse",
        "Yield_Annual_Trim_Mixed_Light": "cr.0.yield_annual_trim_parse",
        "Yield_Percentage_Flower_Tops": "cr.0.flower_yield_percentage_parse",
        "Yield_Percentage_Flower_Smalls": "cr.0.small_yield_percentage_parse",
        "Yield_Percentage_Trim": "cr.0.trim_yield_percentage_parse",
        "Harvest_1_Mixed_Light": "cr.0.cultivars_1_parse",
        "Harvest_2_Mixed_Light": "cr.0.cultivars_2_parse",
        "Harvest_3_Mixed_Light": "cr.0.cultivars_3_parse",
        "Harvest_4_Mixed_Light": "cr.0.cultivars_4_parse",
        "Harvest_5_Mixed_Light": "cr.0.cultivars_5_parse",
        "Harvest_6_Mixed_Light": "cr.0.cultivars_6_parse",
        "Harvest_7_Mixed_Light": "cr.0.cultivars_7_parse",
        "Harvest_8_Mixed_Light": "cr.0.cultivars_8_parse",
        "Harvest_9_Mixed_Light": "cr.0.cultivars_9_parse",
        "Harvest_10_Mixed_Light": "cr.0.cultivars_10_parse",
        "Harvest_11_Mixed_Light": "cr.0.cultivars_11_parse",
        "Harvest_12_Mixed_Light": "cr.0.cultivars_12_parse",
        "Harvest_Date_1_Full_Season": "cr.0.cultivars_1_parse",
        "Harvest_Date_2_Full_Season": "cr.0.cultivars_1_parse",
        #Crop Overview - Autoflower
        "Harvest_Date_1_Autoflower":"cr.1.cultivars_1_parse",
        "Harvest_Date_2_Autoflower":"cr.1.cultivars_2_parse",
        "Yield_per_Square_Foot_Average_Autoflower":"cr.1.avg_yield_pr_sq_ft_parse",
        "Yield_per_Plant_Autoflower":"cr.1.yield_per_plant_parse",
        "Yield_Annual_Flower_Tops_Autoflower":"cr.1.yield_annual_flower_tops_parse",
        "Yield_Annual_Flower_Smalls_Autoflower":"cr.1.yield_annual_flower_smalls_parse",
        "Yield_Annual_Trim_Autoflower":"cr.1.yield_annual_trim_parse",
        "Yield_Percentage_Flower_Tops_Autoflower":"cr.1.flower_yield_percentage_parse",
        "Yield_Percentage_Flower_Smalls_Autoflower":"cr.1.small_yield_percentage_parse",
        "Yield_Percentage_Trim_Autoflower":"cr.1.trim_yield_percentage_parse",
        #Financial Overview
        "Program_Selection": "program_selection",
        "Know_your_Cost_Per_Square_Foot": "fo.0.know_cost_per_sqf_parse",
        "Cost_Per_Square_Foot": "fo.0.cost_per_sqf_parse",
        "Know_your_Cost_per_Lb": "fo.0.know_cost_per_lbs_parse",
        "Cost_per_Lb": "fo.0.cost_per_lbs_parse",
        "Annual_Revenue": "fo.annual_revenue",
        "Annual_Budget": "fo.annual_budget",
        "Price_Target_lb_Flower_Tops": "fo.0.price_target_lb_flower_tops_parse",
        "Price_Target_lb_Flower_Smalls": "fo.0.small_target_price_parse",
        "Price_Target_lb_Trim": "fo.0.trim_target_price_parse",
        "Price_Target_lb_Bucked_Untrimmed": "fo.0.bucked_target_price_parse",
        "Profit_Margin_Target": "fo.0.target_profit_percentage_parse",
        #Financial Overview - Autoflower
        "Know_your_cost_per_square_foot_Autoflower":"fo.1.know_cost_per_sqf_parse",
        "Price_Target_lb_Flower_Tops_Autoflower":"fo.1.price_target_lb_flower_tops_parse",
        "Cost_Per_Square_Foot_Autoflower":"fo.1.cost_per_sqf_parse",
        "Price_Target_lb_Flower_Smalls_Autoflower":"fo.1.small_target_price_parse",
        "Know_your_cost_per_lb_Autoflower":"fo.1.know_cost_per_lbs_parse",
        "Price_Target_lb_Trim_Autoflower":"fo.1.trim_target_price_parse",
        "Cost_per_lb_Autoflower":"fo.1.cost_per_lbs_parse",
        "Price_Target_lb_Bucked_Untrimmed_Autoflower":"fo.1.bucked_target_price_parse",
        "Profit_Margin_Target_Autoflower":"fo.1.target_profit_percentage_parse",
        #Forecast - Mixed Light
        "Square_Feet": "square_feet",
        "Sqf_to_Acres": "sqf_to_acres",
        "Yield_lbs_Mixed_Light_Smalls_Forecast": "yield_lbs_mixed_light_smalls_forecast",
        "Yield_lbs_Mixed_Light_Tops_Forecast": "yield_lbs_mixed_light_tops_forecast",
        "Yield_lbs_Mixed_Light_Trim_Forecast": "yield_lbs_mixed_light_trim_forecast",
        "Annual_Revenue_Mixed_Light_Forecast1": "annual_revenue_mixed_light_forecast1",
        "Annual_Revenue_Mixed_Light_Forecast": "annual_revenue_mixed_light_forecast",
        "Revenue_Mixed_Light_Smalls_Forecast": "revenue_mixed_light_smalls_forecast",
        "Revenue_Mixed_Light_Tops_Forecast": "revenue_mixed_light_tops_forecast",
        "Revenue_Mixed_Light_Trim_Forecast": "revenue_mixed_light_trim_forecast",
        #Forecase - Indoor
        "Yield_lbs_Indoor_Tops": "yield_lbs_indoor_tops",
        "Yield_lbs_Outdoor_Smalls": "yield_lbs_outdoor_smalls",
        "Yield_lbs_Outdoor_Trim": "yield_lbs_outdoor_trim",
        "Total_Annual_Revenue_Indoor": "total_annual_revenue_indoor",
        "Revenue_Indoor_Smalls_Forecast": "revenue_indoor_smalls_forecast",
        "Revenue_Indoor_Tops_Forecast": "revenue_indoor_tops_forecast",
        "Revenue_Indoor_Trim_Forecast": "revenue_indoor_trim_forecast",
    },
    "Accounts":{
        "id": "id",
        "Account_Name": "name",
        "Website": "website",
        "Client_Code": "client_code",
        "Account_Owner": "",
        "Company_Type": "account_category",
        "Account_Legal_Entity_Name": "",
        "Product_of_Interest": "product_of_interest",
        "Company_Account": "",
        "County": "county",
        "Phone": "phone",
        "Region": "region",
        "Contact_1": "employees_parse",
        "Contact_3": "employees_parse",
        "Contact_2": "employees_parse",
        "Owner1": "employees_parse",
        "On-boarded_Active_Client": "",
        "Company_Email": "company_email",
        "Dama_Financial_Approved": "",
        "Curator": "",
        "Modified_By": "",
        "Created_By": "",
        "Can_Provide_Transport": "",
        "Tag": "",
        "Box_Folder_ID": "",
        "About_Company": "",
        "Created_Time": "",
        "Transportation_Method": "transportation_parse",
        "Modified_Time": "",
        "Last_Activity_Time": "",
        "Currency": "",
        "Shipping_Street": "",
        "Shipping_Remarks": "",
        "Shipping_City": "",
        "Shipping_Code": "",
        "Shipping_State": "",
        "Shipping_Country": "",
        "Account_Image": "",
        "Delivery_Windows": "",
        "Loading_Dock_Location": "",
        "Gate_Code": "",
        "Vehicle_Make_Model": "",
        "Drivers_License_Number": "",
        "Driver_s_Name": "",
        "License_Plate_Number": "",
        "Billing_Company_Name": "billing_compony_name",
        #"Preferred_Payment_Method": "preferred_payment_parse",
        "Billing_Street": "billing_street",
        "Bank_Routing_Number": "",
        "Billing_City": "billing_city",
        "Bank_Name": "",
        "Billing_State": "billing_state",
        "Bank_Account_Number": "",
        "Billing_Code": "billing_zip_code",
        "Bank_Street": "",
        "Billing_Country": "",
        "Bank_City": "",
        "Bank_State": "",
        "Bank_Zip_Code": "",
        "Procurement_Rep": "",
        "Logistics_Manager": "logistic_manager_email_parse",
        "Accounting": "",
        "Licenses_List": "licenses",
        "Seller_s_Permit_Box_Link": "",
        "Verified_License_with_State_Agency": "",
        "Seller_s_Permit_Expiration_Date": "",
        "Date_of_License_Verification": "",
        "Credit_Additional_References": "",
        "Credit_Reference_1_Link": "",
        "Credit_Reference_2_Link": "",
        "Credit_Reference_3_Link": "",
        "LinkedIn": "linked_in",
        "Twitter": "twitter",
        "Facebook": "facebook",
        # "Instagram": "instagram",
        "Employees": "",
        "Ownership": "",
        "Ethics_Certifications": "ethics_and_certification_parse",
        "Annual_Revenue": ""
    },
    "Brands_X_Vendors": {
        "Brand": "brands",
        "Vendor": "vendors"
    },
    "Brands_X_Accounts": {
        "Brand": "brands",
        "Account": "accounts"
    },
    "Vendors_X_Licenses": {
        "Licenses_Module": "Licenses_Module",
        "Licenses": "Licenses"
    },
    "Accounts_X_Licenses": {
        "Licenses_Module": "Licenses_Module",
        "Licenses": "Licenses"
    },
    "Vendors_X_Cultivars": {
        "Cultivar_Associations": "Cultivar_Associations",
        "Cultivars": "Cultivars"
    },
    "Vendors_To_DB" : {
        'db_id': 'db_id',
        'id': 'id',
        'layout': 'Layout',
        'name': 'Vendor_Name',
        'Legal_Entity_Names': 'Legal_Entity_Names',
        'Client_Code': 'Client_Code',
        'cultivation_type': 'Cultivation_Type',
        'vendor_type': 'Vendor_Type',
        'county': 'County',
        'region': 'Region',
        'ethics_and_certifications': 'Special_Certifications',
        'appellation': 'Appellations',
        'transportation_methods': 'Transportation_Method',
        'program_details': 'Program_Selection',
        'about': 'About_Company',
        'issues_with_failed_labtest': 'Have_you_ever_had_issues_with_failed_Lab_tests',
        'preferred_payment': 'Preferred_Payment_Method',
        'Farm_Contact_Name': 'Farm_Contact_Name',
        'Last_Name': 'Last_Name',
        'Title': 'Title',
        'company_phone': 'Phone',
        'company_email': 'Email',
        'employees': 'contact_from_crm_parse',
        'no_of_employees': 'Number_of_Employees',
        'Gate_Code': 'Gate_Code',
        'Vehicle_Make_Model': 'Vehicle_Make_Model',
        'Drivers_License_Number': 'Drivers_License_Number',
        'Driver_s_Name': 'Driver_s_Name',
        'License_Plate_Number': 'License_Plate_Number',
        'Sellers_Permit': 'Sellers_Permit',
        'W9_Box_Link': 'W9_Box_Link',
        'Sellers_Permit_Box_Link': 'Sellers_Permit_Box_Link',
        'Sellers_Permit_Expiration_Date': 'Sellers_Permit_Expiration_Date',
        'cultivars_of_interest': 'Cultivars_parse',
        'lighting_type': 'Indoor_Mixed_Lighting_Type',
        'type_of_nutrients': 'Types_of_Nutrients_Used',
        'interested_in_growing_genetics': 'Would_you_grow_genetics_suggested_by_Thrive',
        'which_third_party_lab_do_you_use': 'Which_third_party_lab_do_you_use',
        'lab_test_issues': 'Issues_with_Failed_Lab_Tests',
        'Cultivation_Style_Indoor': 'Cultivation_Style_Indoor',
        'Cultivation_Style_Outdoor': 'Cultivation_Style_Outdoor',
        'Cultivation_Style_Dep_Greenhouse': 'Cultivation_Style_Dep_Greenhouse',
        'Cultivation_Style_Autoflower': 'Cultivation_Style_Autoflower',
        'Annual_Revenue': 'Annual_Revenue',
        'know_annual_budget': 'Know_your_Annual_Budget',
        'annual_budget': 'Yearly_Budget',
        'Yearly_Revenue': 'Yearly_Revenue',
        'Do_you_work_with_other_Distributors': 'Do_you_work_with_other_Distributors',
        'cr.process_on_site': 'Can_you_Process_on_Site',
        'Packaged_Flower_Line': 'Packaged_Flower_Line',
        'Farm_Co_Branding_Interest': 'Farm_Co_Branding_Interest',
        'Marketing_material': 'Marketing_material',
        'Featured_on_our_website_and_social_media': 'Featured_on_our_website_and_social_media',
        'billing_address_street': 'Billing_Street',
        'billing_address_city': 'Billing_City',
        'billing_address_zip_code': 'Billing_Zip_Code',
        'billing_address_state': 'Billing_State',
        'billing_address_country': 'Billing_Country',
        'Do_you_have_a_bank_account': 'Do_you_have_a_bank_account',
        'Bank_Name': 'Bank_Name',
        'Bank_Account_Number': 'Bank_Account_Number',
        'Bank_Routing_Number': 'Bank_Routing_Number',
        'mailing_address_street_line_2': 'Mailing_Street_Line_2',
        'mailing_address_street': 'Shipping_Street',
        'mailing_address_city': 'Shipping_City',
        'mailing_address_zip_code': 'Shipping_Zip_Code',
        'mailing_address_state': 'Shipping_State',
        'mailing_address_country': 'Shipping_Country',
        'Reference_Links': 'Reference_Links',
        'Reference_Link': 'Reference_Link',
        'twitter': 'Twitter',
        'facebook': 'Facebook',
        'linkedIn': 'LinkedIn',
        'instagram': 'Instagram',
        'website': 'Website',
        'IFP_Services_Provided': 'IFP_Services_Provided',
        'Owner': 'Owner',
        'Year_Founded': 'Year_Founded',
        'Round_Trip_Mileage_from_Todd_Rd': 'Round_Trip_Mileage_from_Todd_Rd',
        'GL_Account': 'GL_Account',
        'IFP_Status': 'IFP_Status',
        'Scale': 'Scale',
        'Dama_Approved': 'Dama_Approved',
        'Hide_Internal_Info': 'Hide_Internal_Info',
        'Vendor_Type1': 'Vendor_Type1',
        'Created_Time': 'Created_Time',
        'Modified_Time': 'Modified_Time',
        'Billing_Notes': 'Billing_Notes',
        'Description': 'Description',
        'Box_Folder_ID': 'Box_Folder_ID',
        'Tag': 'Tag',
        'Currency': 'Currency',
        'Record_Image': 'Record_Image',
        'Modified_By': 'Modified_By',
        'Account_Number': 'Account_Number',
        'Annual_Harvests': 'Annual_Harvests',
        'Contract_Box_Link': 'Contract_Box_Link',
        'Created_By': 'Created_By',
        'Vendor_Product_s_Categories': 'Vendor_Product_s_Categories',
        'Irrigation_and_Plumbing': 'Irrigation_and_Plumbing',
        'Lighting': 'Lighting',
        'Trim_Equipment': 'Trim_Equipment',
        'Chemicals_and_Reagents': 'Chemicals_and_Reagents',
        'Greenhouses': 'Greenhouses',
        'Nutrients_Amendments': 'Nutrients_Amendments',
        'Vendor_Product_Categories': 'Vendor_Product_Categories',
        'Motors_and_Pumps': 'Motors_and_Pumps',
        'Lab_Equipment': 'Lab_Equipment',
        'Chilling_Equipment': 'Chilling_Equipment',
        'Product_Storage': 'Product_Storage',
        'Drying': 'Drying',
        'Pesticides_Herbicides_and_Fungicides': 'Pesticides_Herbicides_and_Fungicides',
        'Janitorial_Sanitation': 'Janitorial_Sanitation',
        'Sprayers_Applicators': 'Sprayers_Applicators',
        'Vendor_Service_s_Categories': 'Vendor_Service_s_Categories',
        'Services_Provided': 'Services_Provided'
    },
    "Licenses_To_DB": {
        "legal_business_name": "Name",
        "license_number": "Legal_Business_Name",
        "license_type": "License_Type",
        "expiration_date": "Expiration_Date",
        "business_dba": "Business_DBA",
        "issue_date": "Issue_Date",
        "uploaded_license_to": "License_Box_Link",
        "Owner": "Owner",
        "uploaded_sellers_permit_to": "Sellers_Permit_Box_Link",
        "uploaded_w9_to": "W9_Box_Link",
        "cultivation_type": "Cultivation_Type",
        "license_status": "License_Status",
        "account_name_lookup": "Account_Name_Lookup",
        "vendor_name_lookup": "Vendor_Name_Lookup",
        "verified": "Verified",
        "verified_by": "Verified_by",
        "verified_date": "Verified_Date",
        "premises_address": "Premises_Address",
        "premises_city": "Premises_City",
        "zip_code": "Premises_Zipcode",
        "premises_state": "Premises_State",
        "premises_county": "Premises_County",
        "premises_apn": "Premises_APN_Number",
        "owner_first_name": "Owner_First_Name",
        "owner_last_name": "Owner_Last_Name",
        "license_email": "License_Email",
        "license_phone": "License_Phone",
        "title": "Title",
        "types_of_nutrients": "Types_of_Nutrients",
        "canopy_square_feet": "Canopy_Square_Feet_Mixed_Light",
        "annual_harvests": "Annual_Harvests_Mixed_Light",
        "plants_per_cycle": "Plants_per_Cycle_Mixed_Light",
        "ethics_certification": "Ethics_Certification",
        "region": "Region",
        "appellation": "Appellations",
        "about_farm": "About_Farm",
        "do_you_work_with_other_distributors": "Do_you_work_with_other_distributors",
        "have_you_had_an_issue_with_failed_lab_tests": "Have_you_had_an_issue_with_failed_lab_tests",
        "lab_test_issues_description": "Lab_Test_Issues_Description",
        "outdoor_type": "Outdoor_Type",
        "lighting_type": "Lighting_Type",
        "Can_you_Process_Onsite": "Can_you_Process_Onsite",
        "yield_per_square_foot_average": "Yield_per_Square_Foot_Average_Mixed_Light",
        "yield_per_plant": "Yield_per_Plant_Mixed_Light",
        "yield_annual_flower_tops": "Yield_Annual_Flower_Tops_Mixed_Light",
        "yield_annual_flower_smalls": "Yield_Annual_Flower_Smalls_Mixed_Light",
        "yield_annual_trim": "Yield_Annual_Trim_Mixed_Light",
        "yield_percentage_flower_tops": "Yield_Percentage_Flower_Tops",
        "yield_percentage_flower_smalls": "Yield_Percentage_Flower_Smalls",
        "yield_percentage_trim": "Yield_Percentage_Trim",
        "cultivars_1": "Harvest_1_Mixed_Light",
        "cultivars_2": "Harvest_2_Mixed_Light",
        "cultivars_3": "Harvest_3_Mixed_Light",
        "cultivars_4": "Harvest_4_Mixed_Light",
        "cultivars_5": "Harvest_5_Mixed_Light",
        "cultivars_6": "Harvest_6_Mixed_Light",
        "cultivars_7": "Harvest_7_Mixed_Light",
        "cultivars_8": "Harvest_8_Mixed_Light",
        "cultivars_9": "Harvest_9_Mixed_Light",
        "cultivars_10": "Harvest_10_Mixed_Light",
        "cultivars_11": "Harvest_11_Mixed_Light",
        "cultivars_12": "Harvest_12_Mixed_Light",
        "Harvest_date_1_autoflower": "Harvest_Date_1_Autoflower",
        "harvest_date_2_autoflower": "Harvest_Date_2_Autoflower",
        "harvest_date_1_sull_season": "Harvest_Date_1_Full_Season",
        "harvest_date_2_full_season": "Harvest_Date_2_Full_Season",
        "program_selection": "Program_Selection",
        "know_your_cost_per_square_foot": "Know_your_Cost_Per_Square_Foot",
        "cost_per_square_foot": "Cost_Per_Square_Foot",
        "know_your_cost_per_lb": "Know_your_Cost_per_Lb",
        "cost_per_lb": "Cost_per_Lb",
        "annual_revenue": "Annual_Revenue",
        "annual_budget": "Annual_Budget",
        "price_target_lb_flower_tops": "Price_Target_lb_Flower_Tops",
        "price_target_lb_flower_smalls": "Price_Target_lb_Flower_Smalls",
        "price_target_lb_trim": "Price_Target_lb_Trim",
        "price_target_lb_bucked_untrimmed": "Price_Target_lb_Bucked_Untrimmed",
        "profit_margin_target": "Profit_Margin_Target",
        "square_feet": "Square_Feet",
        "sqf_to_acres": "Sqf_to_Acres",
        "yield_lbs_mixed_light_smalls_forecast": "Yield_lbs_Mixed_Light_Smalls_Forecast",
        "yield_lbs_mixed_light_tops_forecast": "Yield_lbs_Mixed_Light_Tops_Forecast",
        "yield_lbs_mixed_light_trim_forecast": "Yield_lbs_Mixed_Light_Trim_Forecast",
        "annual_revenue_mixed_light_forecast1": "Annual_Revenue_Mixed_Light_Forecast1",
        "annual_revenue_mixed_light_forecast": "Annual_Revenue_Mixed_Light_Forecast",
        "revenue_mixed_light_smalls_forecast": "Revenue_Mixed_Light_Smalls_Forecast",
        "revenue_mixed_light_tops_forecast": "Revenue_Mixed_Light_Tops_Forecast",
        "revenue_mixed_light_trim_forecast": "Revenue_Mixed_Light_Trim_Forecast",
        "yield_lbs_indoor_tops": "Yield_lbs_Indoor_Tops",
        "yield_lbs_outdoor_smalls": "Yield_lbs_Outdoor_Smalls",
        "yield_lbs_outdoor_trim": "Yield_lbs_Outdoor_Trim",
        "total_annual_revenue_indoor": "Total_Annual_Revenue_Indoor",
        "revenue_indoor_smalls_forecast": "Revenue_Indoor_Smalls_Forecast",
        "revenue_indoor_tops_forecast": "Revenue_Indoor_Tops_Forecast",
        "revenue_indoor_trim_forecast": "Revenue_Indoor_Trim_Forecast"
        },
    "Accounts_To_DB":
        {
            "company_name": "Account_Name",
            "company_type": "Company_Type",
            "region": "Region",
            "preferred_payment": "Preferred_Payment_Method",
            "cultivars_of_interest": "Cultivars_parse",
            "ethics_and_certification": "Ethics_Certifications",
            "product_of_interest": "Product_of_Interest",
            "provide_transport": "Can_Provide_Transport",
            "client_code":"Client_Code",
            "company_phone": "Phone",
            "website": "Website",
            "company_email": "Company_Email",
            "owner_name": "",
            "owner_email": "",
            "owner_phone": "",
            "logistic_manager_name": "Logistics_Manager",
            "logistic_manager_email": "Logistics_Manager",
            "logistic_manager_phone": "Logistics_Manager",
            "instagram": "Instagram",
            "linked_in": "LinkedIn",
            "twitter": "Twitter",
            "facebook": "Facebook",
            "billing_compony_name": "Billing_Company_Name",
            "billing_street": "Billing_Street",
            "billing_street_line_2": "",
            "billing_city": "Billing_City",
            "billing_zip_code": "Billing_Code",
            "billing_state": "Billing_State",
            "bank_account_number": "Bank_Account_Number",
            "bank_city": "Bank_City",
            "bank_name": "Bank_Name",
            "bank_routing_number": "Bank_Routing_Number",
            "bank_state": "Bank_State",
            "bank_street": "Bank_Street",
            "bank_zip_code": "Bank_Zip_Code",
            'employees': 'contact_from_crm_parse',
        },
    "Leads":
        {
            "Layout": "layout_parse",
            "Layout_Name": "Layout_Name",
            "Company": "company_name",
            "Last_Name": "last_name",
            "Company_Name": "company_name",
            "First_Name": "first_name",
            "Lead_Source": "heard_from",
            "Owner": "Owner",
            "Company_Type": "Company_Type",
            "Legal_Entity_Name": "Legal_Entity_Name",
            "Email": "email",
            "Phone": "phone",
            "Title": "title",
            "Designation": "Designation",
            "Mobile": "Mobile",
            "Lead_Status": "Lead_Status",
            "Cultivation_Type": "Cultivation_Type",
            "County": "County",
            "Vendor_Type": "vendor_category",
            "Products_of_Interest": "Products_of_Interest",
            "Associated_License": "Associated_License",
            "Created_By": "Created_By",
            "IFP_Status": "IFP_Status",
            "Region": "Region",
            "Modified_By": "Modified_By",
            "Annual_Revenue": "Annual_Revenue",
            "No_of_Employees": "No_of_Employees",
            "Layout": "Layout",
            "Website": "Website",
            "Tag": "Tag",
            "Email_Opt_Out": "Email_Opt_Out",
            "box__Box_Folder_ID": "box__Box_Folder_ID",
            "Created_Time": "Created_Time",
            "Description": "message",
            "Modified_Time": "Modified_Time",
            "Industry": "Industry",
            "Last_Activity_Time": "Last_Activity_Time",
            "Client_Transportation_Options": "Client_Transportation_Options",
            "Converted_Date_Time": "Converted_Date_Time",
            "Is_Record_Duplicate": "Is_Record_Duplicate",
            "Currency": "Currency",
            "City": "City",
            "Mailing_Street": "Mailing_Street",
            "Mailing_State": "Mailing_State",
            "Street": "Street",
            "Mailing_City": "Mailing_City",
            "Mailing_Country": "Mailing_Country",
            "Zip_Code": "Zip_Code",
            "Mailing_Zip_Code": "Mailing_Zip_Code",
            "State": "State",
            "Country": "Country",
            "Record_Image": "Record_Image",
            "Salutation": "Salutation",
            "Canopy_Size": "Canopy_Size",
            "Annual_Production_Lbs": "Annual_Production_Lbs",
            "LinkedIn": "LinkedIn",
            "Full_Name": "Full_Name",
            "Canopy_Sqf_Outdoor": "Canopy_Sqf_Outdoor",
            "Type_of_Nutrients_Used": "Type_of_Nutrients_Used",
            "Instagram": "Instagram",
            "Canopy_Sqf_Indoor": "Canopy_Sqf_Indoor",
            "Indoor_Mixed_Lighting_Type": "Indoor_Mixed_Lighting_Type",
            "Facebook": "Facebook",
            "Twitter": "Twitter",
            "Secondary_Email": "Secondary_Email",
            "Billing_Street": "Billing_Street",
            "Billing_State": "Billing_State",
            "Billing_City": "Billing_City",
            "Billing_Country": "Billing_Country",
            "Billing_Zip_Code": "Billing_Zip_Code",
            "Vehicle_Make_Model": "Vehicle_Make_Model",
            "Drivers_License_Number": "Drivers_License_Number",
            "Name_of_Driver": "Name_of_Driver",
            "License_Plate_Number": "License_Plate_Number",
            "Annual_Revenue_Estimate": "Annual_Revenue_Estimate",
            "Average_Time_Spent_Minutes": "Average_Time_Spent_Minutes",
            "Canopy_Acres_Indoor": "Canopy_Acres_Indoor",
            "Canopy_Mixed_Light_Acres": "Canopy_Mixed_Light_Acres",
            "Canopy_Acres_Outdoor": "Canopy_Acres_Outdoor",
            "Canopy_Sqf_Indoor": "Canopy_Sqf_Indoor",
            "Canopy_Size": "Canopy_Size",
            "Canopy_Sqf_Outdoor": "Canopy_Sqf_Outdoor",
            "Chemicals_and_Reagents": "Chemicals_and_Reagents",
            "Chilling_Equipment": "Chilling_Equipment",
            "Days_Visited": "Days_Visited",
            "Drying": "Drying",
            "Ethics_Certifications": "Ethics_Certifications",
            "First_Visited_URL": "First_Visited_URL",
            "First_Visited_Time": "First_Visited_Time",
            "Greenhouses": "Greenhouses",
            "IFP_Services_Provided": "IFP_Services_Provided",
            "Irrigation_and_Plumbing": "Irrigation_and_Plumbing",
            "Janitorial_Sanitation": "Janitorial_Sanitation",
            "Lab_Equipment": "Lab_Equipment",
            "Whale": "Whale",
            "Lighting": "Lighting",
            "Last_Visited_Time": "Last_Visited_Time",
            "Motors_and_Pumps": "Motors_and_Pumps",
            "Number_Of_Chats": "Number_Of_Chats",
            "Nutrients_Amendments": "Nutrients_Amendments",
            "Pesticides_Herbicides_and_Fungicides": "Pesticides_Herbicides_and_Fungicides",
            "PPE": "PPE",
            "Prediction_Score": "Prediction_Score",
            "Product_Storage": "Product_Storage",
            "Referrer": "Referrer",
            "Revenue_Mixed_Light_Smalls": "Revenue_Mixed_Light_Smalls",
            "Revenue_Mixed_Light_Tops": "Revenue_Mixed_Light_Tops",
            "Revenue_Mixed_Light_Trim": "Revenue_Mixed_Light_Trim",
            "Show_Internal_Information": "Show_Internal_Information",
            "Sprayers_Applicators": "Sprayers_Applicators",
            "Trim_Equipment": "Trim_Equipment",
            "Vendor_Product_s_Categories": "Vendor_Product_s_Categories",
            "Vendor_Service_s_Categories": "Vendor_Service_s_Categories",
            "Visitor_Score": "Visitor_Score",
            "Yield_lbs_Mixed_Light_Bucked_Untrimmed": "Yield_lbs_Mixed_Light_Bucked_Untrimmed",
            "Yield_lbs_Mixed_Light_Smalls": "Yield_lbs_Mixed_Light_Smalls",
            "Mixed_Light_Tops_Estimate": "Mixed_Light_Tops_Estimate",
            "Yield_lbs_Mixed_Light_Trim": "Yield_lbs_Mixed_Light_Trim",
            "Yield_lbs_Outdoor_Bucked_Forecast": "Yield_lbs_Outdoor_Bucked_Forecast",
            "Yield_lbs_Outdoor_Smalls": "Yield_lbs_Outdoor_Smalls",
            "Yield_lbs_Outdoor_Tops": "Yield_lbs_Outdoor_Tops",
            "Yield_lbs_Outdoor_Trim": "Yield_lbs_Outdoor_Trim",
        },
    "Cultivars":
        {
            "Description": "description",
            "Effects": "effect",
            "Name": "cultivar_name",
            "CBD_Range": "cbd_range",
            "Record_Image": "cultivar_image",
            "THCv_Range": "thcv_range",
            "Modified_By": "modified_by_parse",
            "Terpenes_Secondary": "terpenes_secondary",
            "Parent_2": "parent_2_parse",
            "Parent_1": "parent_1_parse",
            "id": "cultivar_crm_id",
            "Modified_Time": "modify_time",
            "Created_Time": "create_time",
            "Flavor": "flavor",
            "Type": "cultivar_type",
            "THC_Range": "thc_range",
            "CBG_Range": "cbg_range",
            "Created_By": "created_by_parse",
            "Terpenes": "terpenes_primary"
        },
    "Testing":
        {
            "id": "labtest_crm_id",
            "Abamectin": "Abamectin",
            "Acephate": "Acephate",
            "Acequinocyl": "Acequinocyl",
            "Acetamiprid": "Acetamiprid",
            "Aflatoxin_B1": "Aflatoxin_B1",
            "Aflatoxin_B2": "Aflatoxin_B2",
            "Aflatoxin_G1": "Aflatoxin_G1",
            "Aflatoxin_G2": "Aflatoxin_G2",
            "Aldicarb": "Aldicarb",
            "Arsenic": "Arsenic",
            "Aspergillus": "Aspergillus",
            "Aspergillus_flavus": "Aspergillus_flavus",
            "Aspergillus_fumigatus": "Aspergillus_fumigatus",
            "Aspergillus_nigers": "Aspergillus_nigers",
            "Aspergillus_terreus": "Aspergillus_terreus",
            "Associated_Vendor": "Associated_Vendor",
            "Azoxystrobin": "Azoxystrobin",
            "B_Caryophyllene_oxide": "B_Caryophyllene_oxide",
            "Single_Line_114": "Benzene",
            "Bifenazate": "Bifenazate",
            "Bifenthrin": "Bifenthrin",
            "Single_Line_93": "Borneol",
            "Boscalid": "Boscalid",
            "Box_Folder_Name": "Box_Folder_Name",
            "Box_Lab_Test_Folder_ID": "Box_Lab_Test_Folder_ID",
            "Box_Link": "Box_Link",
            "CBC": "CBC_parse",
            "CBCA": "CBCA_parse",
            "CBD": "CBD_parse",
            "CBDA": "CBDA_parse",
            "CBDV": "CBDV_parse",
            "CBDVA": "CBDVA_parse",
            "CBG": "CBG_parse",
            "CBGA": "CBGA_parse",
            "CBL": "CBL_parse",
            "CBN": "CBN_parse",
            "Cadmium": "Cadmium",
            "Single_Line_80": "Camphene",
            "Camphor": "Camphor",
            "Cannabinoids": "Cannabinoids_parse",
            "Captan": "Captan",
            "Carbaryl": "Carbaryl",
            "Carbofuran": "Carbofuran",
            "Chlordane": "Chlordane",
            "Chlorfenapyr": "Chlorfenapyr",
            "Single_Line_115": "Chloroform",
            "Chlorpyrifos": "Chlorpyrifos",
            "Chlortraniliprole": "Chlortraniliprole",
            "Client_Code": "Client_Code",
            "Clofentazine": "Clofentazine",
            "Coumaphos": "Coumaphos",
            "Created_Time": "Created_Time_parse",
            "Cultivar": "Cultivar",
            "Cyfluthrin": "Cyfluthrin",
            "Cypermethrin": "Cypermethrin",
            "Daminozide": "Daminozide",
            "Date_Harvested": "Date_Harvested_parse",
            "Date_Received": "Date_Received_parse",
            "Date_Reported": "Date_Reported_parse",
            "Date_Tested": "Date_Tested_parse",
            "Diazinon": "Diazinon",
            "Single_Line_113": "Dichloroethane",
            "Dichlorvos": "Dichlorvos",
            "Dimethoate": "Dimethoate",
            "Dimethomorph": "Dimethomorph",
            "E_Coli": "E_Coli",
            "Eicosane": "Eicosane",
            "Ethoprop": "Ethoprop",
            "Single_Line_116": "Ethylene_Oxide",
            "Etofenprox": "Etofenprox",
            "Etoxazole": "Etoxazole",
            "Single_Line_85": "Eucalyptol",
            "Single_Line_99": "Farnesene",
            "Single_Line_90": "Fenchol",
            "Fenhexamid": "Fenhexamid",
            "Fenoxycarb": "Fenoxycarb",
            "Fenpyroximate": "Fenpyroximate",
            "Single_Line_178": "Filth_Foreign_Matter",
            "Fipronil": "Fipronil",
            "Flonicamid": "Flonicamid",
            "Fludoxinil": "Fludoxinil",
            "Single_Line_95": "Geraniol",
            "Guaiol": "Guaiol",
            "Single_Line_175": "Heavy_Metals",
            "Hexythiazox": "Hexythiazox",
            "Single_Line_180": "Homogeneity",
            "Imazilil": "Imazilil",
            "Imidacloprid": "Imidacloprid",
            "Inventory_SKU": "Inventory_SKU",
            "Kresoxim_methyl": "Kresoxim_methyl",
            "L_fenchone": "L_fenchone",
            "Last_Activity_Time": "Last_Activity_Time_parse",
            "Lead": "Lead",
            "Single_Line_89": "Linalool",
            "Malathion": "Malathion",
            "Single_Line_92": "Menthol",
            "Mercury": "Mercury",
            "Metalaxyl": "Metalaxyl",
            "Methiocarb": "Methiocarb",
            "Methomyl": "Methomyl",
            "Single_Line_117": "Methylene_chloride",
            "Mevinphos": "Mevinphos",
            "Single_Line_177": "Microbiological_Contamination",
            "Modified_By": "Modified_By",
            "Modified_Time": "Modified_Time_parse",
            "Single_Line_179": "Moisture",
            "Myclobutanil": "Myclobutanil",
            "Mycotoxins_PASS_FAIL": "Mycotoxins_PASS_FAIL",
            "Single_Line_82": "Myrcene",
            "Naled": "Naled",
            "Name": "Name",
            "Ochratoxin": "Ochratoxin",
            "Single_Line_86": "Ocimene",
            "Oxamyl": "Oxamyl",
            "Paclobutrazole": "Paclobutrazole",
            "Parathion_methyl": "Parathion_methyl",
            "Pentachloronitrobenzene": "Pentachloronitrobenzene",
            "Permethrin": "Permethrin",
            "Single_Line_174": "Pesticides",
            "Phosmet": "Phosmet",
            "Piperonyl_butoxide": "Piperonyl_butoxide",
            "Prallethrin": "Prallethrin",
            "Propiconazole": "Propiconazole",
            "Propoxur": "Propoxur",
            "Single_Line_91": "Pulegone",
            "Pyrethrins": "Pyrethrins",
            "Pyridaben": "Pyridaben",
            "QC_Batch_es": "QC_Batch_es",
            "Single_Line_84": "R_Limonene",
            "Record_Image": "Record_Image",
            "Relative_Standard_Deviation": "Relative_Standard_Deviation",
            "Sabinene": "Sabinene",
            "Salmonella": "Salmonella",
            "Sample_I_D": "Sample_I_D",
            "Sample_Type": "Sample_Type",
            "Service_Time": "Service_Time",
            "Spinatoram": "Spinatoram",
            "Spinosad": "Spinosad",
            "Spiromesifen": "Spiromesifen",
            "Spirotetramat": "Spirotetramat",
            "Spiroxamine": "Spiroxamine",
            "THC": "THC_parse",
            "THCA": "THCA_parse",
            "THCV": "THCV_parse",
            "THCVA": "THCVA_parse",
            "Tag": "Tag",
            "Tebuconazole": "Tebuconazole",
            "Single_Line_88": "Terpinolene",
            "Test_Upload": "Test_Upload",
            "Tests_Performed": "Tests_Performed",
            "Thiacloprid": "Thiacloprid",
            "Thiamethoxam": "Thiamethoxam",
            "Total_Aflatoxin": "Total_Aflatoxin",
            "Total_CBD": "Total_CBD_parse",
            "Total_Cannabinoids": "Total_Cannabinoids_parse",
            "Single_Line_176": "Total_Residual_Solvent",
            "Total_THC": "Total_THC_parse",
            "Total_Terpenes": "Total_Terpenes",
            "Single_Line_141": "Total_Xylenes",
            "Single_Line_118": "Trichloroethylene",
            "Trifloxystrobin": "Trifloxystrobin",
            "Single_Line_98": "Valencene",
            "a_phellandrene": "a_phellandrene",
            "Single_Line_121": "acetone",
            "Single_Line_133": "acetonitrile",
            "alpha_Bisabolol": "alpha_Bisabolol",
            "Single_Line_97": "alpha_Humulene",
            "Single_Line_94": "alpha_Terpineol",
            "Single_Line_79": "alpha_pinene",
            "Single_Line_96": "beta_Caryophyllene",
            "Single_Line_81": "beta_Pinene",
            "Single_Line_143": "butanone",
            "cis_Nerolidol": "cis_Nerolidol",
            "d_8_THC": "d_8_THC_parse",
            "Single_Line_122": "ethanol",
            "Single_Line_142": "ether",
            "Single_Line_134": "ethyl_acetate",
            "Single_Line_138": "four_methyl_two_pentanone",
            "Single_Line_87": "gamma_Terpinene",
            "Single_Line_125": "methanol",
            "Single_Line_135": "n_Heptane",
            "Single_Line_119": "n_butane",
            "Single_Line_124": "n_hexane",
            "Single_Line_120": "n_pentane",
            "Single_Line_129": "one_butanol",
            "Single_Line_130": "one_pentanol",
            "Single_Line_132": "one_propanol",
            "phytol": "phytol",
            "Single_Line_140": "propane",
            "Single_Line_137": "tert_butyl_methyl_ether",
            "Single_Line_83": "three_Carene",
            "Single_Line_128": "three_methyl_one_butanol",
            "Single_Line_139": "toluene",
            "trans_Nerolidol": "trans_Nerolidol",
            "Single_Line_131": "two_butanol",
            "Single_Line_123": "two_methyl_butane",
            "Single_Line_136": "two_methyl_one_propanol",
            "Single_Line_127": "two_methyl_propane",
            "Single_Line_126": "two_propanol"
        },
    "Books_Customer":
        {
            'contact_id': 'contact_id',
            'contact_name': 'name',
            'company_name': 'brand_name',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'designation': 'designation',
            'department': 'department',
            'website': 'website',
            'email': 'company_email',
            'phone': 'company_phone',
            'mobile': 'mobile',
            'billing_address': 'billing_address_parse',
            'shipping_address': 'mailing_address_parse',
            'contact_persons': 'employees_parse',
            'contact_type': 'contact_type_parse',
        }
}

VENDOR_TYPES = {
    "cultivation": "Cultivator",
    "nursery": "Nursery",
    "manufacturing": "Manufacturer",
    "distribution": "Distributor",
    "retail": "Retailer",
    "processing": "Processor",
    "testing": "Testing",
    "event": "Event",
    "brand": "Brand",
    "hemp": "Hemp",
    "ancillary products": "Ancillary Products",
    "ancillary services": "Ancillary Services",
    "investment": "Investor",
    "patient": "Patient",
    "healthcare": "Healthcare"
}

# Display value : Actual Value
# ACCOUNT_TYPES = {
#  "Ancillary Products": "Vendor - Equipment and Supplies",
#  "Ancillary Services": "Professional Services",
#  "Brand - Concentrates": "Brand",
#  "Brand - Edibles": "Edibles",
#  "Brand - Flower": "Flower Brand",
#  "Brand - Vape Pens": "Vape Pens",
#  "Cultivation": "Cultivator",
#  "Delivery": "Delivery",
#  "Distribution": "Distributor",
#  "Hemp": "Hemp",
#  "Investment": "Investor",
#  "Legal": "Legal",
#  "Lending": "Lender",
#  "Manufacturing": "Manufacturing - Type 6",
#  "Marketing": "Marketing",
#  "Nursery": "Nursery",
#  "Processing": "Processing",
#  "Retail": "Retail",
#  "Transportation": "Transport"}

ACCOUNT_TYPES = {
    "cultivator":"Cultivator",
}


