role_map = {
    "License Owner": "license_owner",
    "Farm Manager": "farm_manager",
    "Sales/Inventory": "sales_or_inventory",
    "Logistics": "logistics",
    "Billing": "billing",
    "Owner": "owner",
}


DEFAULT_ROLE_PERM = {
    'License Owner': [
        "add_profile_contact",
        "delete_profile_contact",
        "edit_billing_address",
        "edit_billing_information",
        "edit_mailing_address",
        "edit_profile_contact",
        "edit_shipping_address",
        "view_billing_address",
        "view_billing_information",
        "view_mailing_address",
        "view_profile_contact",
        "view_shipping_address",
        "add_license",
        "delete_license",
        "edit_license",
        "view_license",
        "add_inventory",
        "edit_inventory",
        "view_inventory",
        "view_sales",
        "add_brand",
        "delete_brand",
        "edit_brand",
        "edit_organization",
        "edit_organization_role",
        "edit_organization_user",
        "send_organization_invite",
        "view_brand",
        # "view_organization",
        "view_organization_role",
        "view_organization_user",
        "add_crop_overview",
        "add_cultivation_overview",
        "add_financial_overview",
        "add_program_overview",
        "change_license_profile_logo",
        "delete_crop_overview",
        "delete_cultivation_overview",
        "delete_financial_overview",
        "delete_program_overview",
        "edit_crop_overview",
        "edit_cultivation_overview",
        "edit_financial_overview",
        "edit_license_ethics_Certifications",
        "edit_license_profile",
        "edit_license_profile_about",
        "edit_license_profile_appellation",
        "edit_license_profile_brand_association",
        "edit_license_profile_lighting_type",
        "edit_license_profile_region",
        "edit_license_type_of_nutrients",
        "edit_profile_contact_business_email",
        "edit_profile_contact_instagram",
        "edit_profile_contact_linkedin",
        "edit_profile_contact_personal_phone",
        "edit_profile_contact_website",
        "edit_program_overview",
        "view_crop_overview",
        "view_cultivation_overview",
        "view_financial_overview",
        "view_license_ethics_Certifications",
        "view_license_profile",
        "view_license_profile_about",
        "view_license_profile_appellation",
        "view_license_profile_brand_association",
        "view_license_profile_lighting_type",
        "view_license_profile_logo",
        "view_license_profile_region",
        "view_license_type_of_nutrients",
        "view_profile_contact_business_email",
        "view_profile_contact_instagram",
        "view_profile_contact_linkedin",
        "view_profile_contact_personal_phone",
        "view_profile_contact_website",
        "view_program_overview",

        "view_billing_overview",
        "view_orders_estimates",
        'add_orders_estimates',
        'edit_orders_estimates',
        'delete_orders_estimates',
        "view_sales_orders",
        "view_purchase_orders",
        "view_bills",
        "view_invoices",
        "view_payments_made",
        "view_payments_received",
        "view_billing_overview_bank_information",
        "edit_billing_overview_bank_information",
        "view_billing_overview_bank_address",
        "edit_billing_overview_bank_address",
        "view_billing_overview_preferred_payment",
        "edit_billing_overview_preferred_payment",
        "view_billing_overview_license_premises_address",
        "edit_billing_overview_license_premises_address",
    ],
    'Farm Manager': [
        "view_cultivation_overview",
        "add_cultivation_overview",
        "edit_cultivation_overview",
        "delete_cultivation_overview",
        "view_crop_overview",
        "add_crop_overview",
        "edit_crop_overview",
        "delete_crop_overview",
    ],
    'Sales/Inventory': [
        "view_sales",
        "view_inventory",
        "add_inventory",
        "edit_inventory",
    ],
    'Billing': [
        "view_profile_contact",
        "add_profile_contact",
        "edit_profile_contact",
        "delete_profile_contact",
        "view_billing_information",
        "edit_billing_information",
        "view_billing_address",
        "edit_billing_address",
        "view_shipping_address",
        "edit_shipping_address",
        "view_mailing_address",
        "edit_mailing_address",
        "view_program_overview",
    ],
    'Logistics': [
        "view_license",
        "view_brand",
        "view_license_profile",
    ]
}
