accounts_to_vendors_dict = {
    'id': 'Associated_Account_Record',
    'About_Company': 'About_Company',
    'Account_Name': 'Vendor_Name',
    'Account_Business_DBA': 'Legal_Entity_Names',
    'Tier_Selection': 'Program_Selection',
    'Record_Image': 'Record_Image',
    'Annual_Revenue': 'Annual_Revenue',
    # 'Associated_Vendor_Record': '',
    'Bank_Account_Number': 'Bank_Account_Number',
    'Bank_City': 'Bank_City',
    'Bank_Country': 'Bank_Country',
    'Bank_Name': 'Bank_Name',
    'Bank_Routing_Number': 'Bank_Routing_Number',
    'Bank_States': 'Bank_State',
    'Bank_Street': 'Bank_Street',
    'Bank_Zip_Code': 'Bank_Zip_Code',
    'Billing_City': 'Billing_City',
    'Billing_Code': 'Billing_Zip_Code',
    # 'Billing_Company_Name': '',
    'Billing_Country': 'Billing_Country',
    'Billing_Notes': 'Billing_Notes',
    'Billing_State': 'Billing_State',
    'Billing_Street': 'Billing_Street',
    # 'box__Box_Folder_ID': 'Box_Folder_ID', #######################
    # 'Box_Folder_URL': 'Box_Folder_URL', ##########################
    'Business_Structure': 'Business_Structure',
    # 'Can_Provide_Transport': '',
    'Client_Code': 'Client_Code',
    # 'Company_Account': '',
    'Company_Email': 'Email',
    # 'Company_Type': '',
    'County': 'County',
    # 'Created_By': 'Created_By',  ###########################
    'Additional_References': 'Reference_Links',
    # 'Reference_1_Link': '',
    # 'Reference_2_Link': '',
    # 'Credit_Reference_3_Link': '',
    'Cultivars_of_Interest': 'Cultivars',
    # 'Curator': '',
    'Currency': 'Currency',
    'Dama_Approved': 'Dama_Approved',
    'Default_Licenses_for_Transactions_for_Books': 'Default_License_for_Transactions_in_Books',
    # 'Delivery_Windows': '',
    # 'Digital_Score_Act': '',
    'Do_you_have_a_bank_account': 'Do_you_have_a_bank_account',
    'Driver_s_Name': 'Driver_s_Name',
    'Drivers_License_Number': 'Drivers_License_Number',
    'EIN': 'EIN',
    'Employees': 'Number_of_Employees',
    'Ethics_Certifications': 'Special_Certifications',

    'Exchange_Rate': 'Exchange_Rate',
    'Facebook': 'Facebook',
    'Gate_Code': 'Gate_Code',
    'Instagram': 'Instagram',
    # 'License_2': '',
    'License_Plate_Number': 'License_Plate_Number',
    'Licenses': 'Licenses',
    'LinkedIn': 'LinkedIn',
    # 'Loading_Dock_Location': '',
    'Round_Trip_Mileage_from_Todd_Rd': 'Round_Trip_Mileage_from_Todd_Rd',
    # 'Modified_By': 'Modified_By', #########################
    # 'Ownership': '',
    # 'Owner': 'Owner', ###########################
    'Phone': 'Phone',
    'Preferred_Payment_Method': 'Preferred_Payment_Method',
    # 'Account_Contacts': '',
    # 'Product': '',
    'Region': 'Region',
    'Seller_s_Permit_Box_Link': 'Sellers_Permit_Box_Link',
    'Seller_s_Permit_Expiration_Date': 'Sellers_Permit_Expiration_Date',
    'Shipping_City': 'Shipping_City',
    'Shipping_Code': 'Shipping_Zip_Code',
    'Shipping_Country': 'Shipping_Country',
    # 'Shipping_Remarks': '',
    'Shipping_State': 'Shipping_State',
    'Shipping_Street': 'Shipping_Street',
    'SSN': 'SSN',
    'Transportation_Method': 'Transportation_Method',
    'Twitter': 'Twitter',
    # 'Show_Internal_Use_Only_Fields': '',
    'Vehicle_Make_Model': 'Vehicle_Make_Model',
    # 'Verified_License_with_State_Agency': '',
    'Website': 'Website',
}
