"""
URL Configuration
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.urls import path
from rest_framework.routers import SimpleRouter

from ..views import (
    GetBoxTokensView,
    InventoryView,
    GetPickListView,
    GetLeadsCompanyTypeListView,
    EstimateView,
    ContactView as ContactViewBooks,
    CRMContactView,
    SearchCultivars,
    LeadView,
    GetBoxSharedLink,
    LeadSourcesView,
    PurchaseOrderView,
    CRMVendorView,
    VendorPaymentView,
    InvoiceView,
    AccountSummaryView,
    VendorCreditView,
    EstimateTaxView,
    GetTaxView,
    ContactAddressView,
    GetPickListAccountView,
    EstimateStatusView,
    ClientCodeView,
    VendorClientCodeView,
    EstimateSignView,
    EstimateSignCompleteView,
    GetDocumentStatus,
    GetSignURL,
    TemplateSignView,
    GetDistanceView,
    GetSalesPersonView,
    GetTemplateStatus,
    CustomerPaymentView,
    GetBoxTokenAuthenticationView,
    BillView,
    SalesOrderView,
    EstimateAddressView,
    ContactPersonView,
    CRMVendorTierView,
    GetNewsFeedView,
    GetRecordView,
    LabTestView,
    GetAutoComplete,
    NotificationView,
    DownloadSignDocumentView,
    CampaignView,
    MarkEstimateView,
    ApproveEstimateView,
    MarkSalesOrderView,
    ApproveSalesOrderView,
    SalesOrderSubStatusesView,
    MarkPurchaseOrderView,
    ApprovePurchaseOrderView,
    MarkInvoiceView,
    ApproveInvoiceView,
    MarkBillView,
    ApproveBillView,
    ConvertEstimateToSalesOrder,
    ConvertSalesOrderToInvoice,
    ChatbotView,
    ConvertEstimateToInvoice,
    ConvertSalesOrderToPurchaseOrder,
    ConfiaCallbackView,
)

app_name = "integration"

router = SimpleRouter()

urlpatterns = [
    path(r'box/link/', GetBoxSharedLink.as_view(), name='get_shared_link'),
    path(r'integration/box/', GetBoxTokensView.as_view(), name='box'),
    path(r'notify/', NotificationView.as_view(), name='notification'),
    path(r'integration/box-aws/',
         GetBoxTokenAuthenticationView.as_view(), name='box-token-authentication'),
    path(r'integration/confia/callback/', ConfiaCallbackView.as_view(), name="confia-callback"),
    path(r'crm/search/cultivar', SearchCultivars.as_view(), name='search_cultivar'),
    path(r'crm/picklist/', GetPickListView.as_view(), name='get_picklist'),
    path(r'crm/picklist/leads-company-type', GetLeadsCompanyTypeListView.as_view(), name='get_picklist'),
    path(r'crm/account-picklist/', GetPickListAccountView.as_view(),
         name='get_account_picklist'),
    path(r'crm/contact/', CRMContactView.as_view(), name='list_crm_contacts'),
    path(r'crm/', GetRecordView.as_view(), name='get_crm_record'),
    path(r'crm/lead/', LeadView.as_view(), name='create_lead'),
    path(r'crm/lead-sources/', LeadSourcesView.as_view(), name='get_lead_sources'),
    path(r'crm/vendor/', CRMVendorView.as_view(), name='get_vendor'),
    path(r'crm/vendor-tier/', CRMVendorTierView.as_view(), name='update_tier'),
    path(r'crm/account-client-code/', ClientCodeView.as_view(),
         name='get_account_client_code'),
    path(r'crm/vendor-client-code/', VendorClientCodeView.as_view(),name='get_vendor_client_code'),
    path(r'books/estimate/', EstimateView.as_view(), name='estimate'),
    path(r'books/estimate-address/', EstimateAddressView.as_view(), name='estimate_address'),
    path(r'books/contact/', ContactViewBooks.as_view(), name='books-contact'),
    path(r'books/contact-person/', ContactPersonView.as_view(), name='contact-person'),
    path(r'books/contact-address/',
         ContactAddressView.as_view(), name='contact_address'),
    path(r'books/purchase-order/',
         PurchaseOrderView.as_view(), name='purchase_order'),
    path(r'books/vendor-payment/',
         VendorPaymentView.as_view(), name='vendor_payment'),
    path(r'books/customer-payment/',
         CustomerPaymentView.as_view(), name='customer_payment'),
    path(r'books/invoice/', InvoiceView.as_view(), name='invoices'),
    path(r'books/bill/', BillView.as_view(), name='bills'),
    path(r'books/sales-order/', SalesOrderView.as_view(), name='sales-orders'),
    path(r'books/vendor-credits/',
         VendorCreditView.as_view(), name='vendor_credits'),
    path(r'books/account-summary/',
         AccountSummaryView.as_view(), name='account_summary'),
    path(r'books/calculate-tax/', EstimateTaxView.as_view(), name='calculate-tax'),
    path(r'books/tax/', GetTaxView.as_view(), name='get-tax'),
    path(r'books/estimate-status/',
         EstimateStatusView.as_view(), name='update_status'),
    path(r'books/sign-estimate/', EstimateSignView.as_view(), name='sign-estimate'),
    path(r'books/signed-estimate/',
         EstimateSignCompleteView.as_view(), name='sined-estimate'),
    path(r'books/sign-status/', GetDocumentStatus.as_view(), name='get-sign-status'),
    path(r'books/sign-url/', GetSignURL.as_view(), name='get-sign-url'),
    path(r'sign/template/', TemplateSignView.as_view(), name='sign_template'),
    path(r'sign/template-status/',
         GetTemplateStatus.as_view(), name='template_status'),
    path(r'integration/distance/', GetDistanceView.as_view(), name='get_distance'),
    path(r'crm/sales-person/', GetSalesPersonView.as_view(),
         name='get_sales_person'),
    path(r'news/', GetNewsFeedView.as_view(), name='news-feed'),
    path(r'crm/labtest/<str:labtest_id>/', LabTestView.as_view(), name='labtest'),
    path(r'autocomplete/', GetAutoComplete.as_view(), name="address-autocomplete"),
    path(r'sign/download/', DownloadSignDocumentView.as_view(), name="download-sign-document"),
    path(r'campaign/', CampaignView.as_view(), name="campaign"),
    path(r'books/estimate/status/', MarkEstimateView.as_view(), name="mark-estimate"),
    path(r'books/estimate/approve/', ApproveEstimateView.as_view(), name="approve-estimate"),
    path(r'books/sales-order/status/', MarkSalesOrderView.as_view(), name="mark-salesorder"),
    path(r'books/sales-order/approve/', ApproveSalesOrderView.as_view(), name="approve-salesorder"),
    path(r'books/purchase-order/status/', MarkPurchaseOrderView.as_view(), name="mark-purchaseorder"),
    path(r'books/purchase-order/approve/', ApprovePurchaseOrderView.as_view(), name="approve-purchaseorder"),
    path(r'books/invoice/status/', MarkInvoiceView.as_view(), name="mark-invoice"),
    path(r'books/invoice/approve/', ApproveInvoiceView.as_view(), name="approve-invoice"),
    path(r'books/bill/status/', MarkBillView.as_view(), name="mark-bill"),
    path(r'books/bill/approve/', ApproveBillView.as_view(), name="approve-bill"),
    path(r'books/sales-order/sub-statuses/', SalesOrderSubStatusesView.as_view(), name="sales-order-sub-statuses"),
    path(r'books/estimate/convert/sales-order/', ConvertEstimateToSalesOrder.as_view(), name="convert-estimate-to-salesorder"),
    path(r'books/sales-order/convert/invoice/', ConvertSalesOrderToInvoice.as_view(), name="convert-so-to-invoice"),
    path(r'books/estimate/convert/invoice/', ConvertEstimateToInvoice.as_view(), name="convert-estimate-to-invoice"),
    path(r'books/sales-order/convert/purchase-order/', ConvertSalesOrderToPurchaseOrder.as_view(), name="convert-so-to-po"),
    path(r'bot/', ChatbotView.as_view(), name="chat-bot"),
] + router.urls
