# Generated by Django 2.2 on 2021-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalonboardinginvite',
            name='is_user_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalonboardinginvite',
            name='is_user_do_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
